package com.doerit.model.diagnostic;

import com.doerit.model.InsertUpdate;

import java.util.Date;

public class DietaryHistory implements InsertUpdate {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_patient_dietary_history.ID
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_patient_dietary_history.SUGER_CONSUMPTION
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    private String sugerConsumption;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_patient_dietary_history.OTHER_FREQUENCY
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    private String otherFrequency;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_patient_dietary_history.BEVERAGES
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    private String beverages;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_patient_dietary_history.COMMENT
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    private String comment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_patient_dietary_history.STATUS
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_patient_dietary_history.SORT_ORDER
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    private Integer sortOrder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_patient_dietary_history.INSERT_USER_ID
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    private String insertUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_patient_dietary_history.INSERT_DATETIME
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    private Date insertDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_patient_dietary_history.UPDATE_USER_ID
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    private String updateUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_patient_dietary_history.UPDATE_DATETIME
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    private Date updateDatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_patient_dietary_history.ID
     *
     * @return the value of tbl_patient_dietary_history.ID
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_patient_dietary_history.ID
     *
     * @param id the value for tbl_patient_dietary_history.ID
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_patient_dietary_history.SUGER_CONSUMPTION
     *
     * @return the value of tbl_patient_dietary_history.SUGER_CONSUMPTION
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public String getSugerConsumption() {
        return sugerConsumption;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_patient_dietary_history.SUGER_CONSUMPTION
     *
     * @param sugerConsumption the value for tbl_patient_dietary_history.SUGER_CONSUMPTION
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public void setSugerConsumption(String sugerConsumption) {
        this.sugerConsumption = sugerConsumption == null ? null : sugerConsumption.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_patient_dietary_history.OTHER_FREQUENCY
     *
     * @return the value of tbl_patient_dietary_history.OTHER_FREQUENCY
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public String getOtherFrequency() {
        return otherFrequency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_patient_dietary_history.OTHER_FREQUENCY
     *
     * @param otherFrequency the value for tbl_patient_dietary_history.OTHER_FREQUENCY
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public void setOtherFrequency(String otherFrequency) {
        this.otherFrequency = otherFrequency == null ? null : otherFrequency.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_patient_dietary_history.BEVERAGES
     *
     * @return the value of tbl_patient_dietary_history.BEVERAGES
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public String getBeverages() {
        return beverages;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_patient_dietary_history.BEVERAGES
     *
     * @param beverages the value for tbl_patient_dietary_history.BEVERAGES
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public void setBeverages(String beverages) {
        this.beverages = beverages == null ? null : beverages.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_patient_dietary_history.COMMENT
     *
     * @return the value of tbl_patient_dietary_history.COMMENT
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_patient_dietary_history.COMMENT
     *
     * @param comment the value for tbl_patient_dietary_history.COMMENT
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_patient_dietary_history.STATUS
     *
     * @return the value of tbl_patient_dietary_history.STATUS
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_patient_dietary_history.STATUS
     *
     * @param status the value for tbl_patient_dietary_history.STATUS
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_patient_dietary_history.SORT_ORDER
     *
     * @return the value of tbl_patient_dietary_history.SORT_ORDER
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public Integer getSortOrder() {
        return sortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_patient_dietary_history.SORT_ORDER
     *
     * @param sortOrder the value for tbl_patient_dietary_history.SORT_ORDER
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public void setSortOrder(Integer sortOrder) {
        this.sortOrder = sortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_patient_dietary_history.INSERT_USER_ID
     *
     * @return the value of tbl_patient_dietary_history.INSERT_USER_ID
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public String getInsertUserId() {
        return insertUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_patient_dietary_history.INSERT_USER_ID
     *
     * @param insertUserId the value for tbl_patient_dietary_history.INSERT_USER_ID
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public void setInsertUserId(String insertUserId) {
        this.insertUserId = insertUserId == null ? null : insertUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_patient_dietary_history.INSERT_DATETIME
     *
     * @return the value of tbl_patient_dietary_history.INSERT_DATETIME
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public Date getInsertDatetime() {
        return insertDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_patient_dietary_history.INSERT_DATETIME
     *
     * @param insertDatetime the value for tbl_patient_dietary_history.INSERT_DATETIME
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public void setInsertDatetime(Date insertDatetime) {
        this.insertDatetime = insertDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_patient_dietary_history.UPDATE_USER_ID
     *
     * @return the value of tbl_patient_dietary_history.UPDATE_USER_ID
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public String getUpdateUserId() {
        return updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_patient_dietary_history.UPDATE_USER_ID
     *
     * @param updateUserId the value for tbl_patient_dietary_history.UPDATE_USER_ID
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public void setUpdateUserId(String updateUserId) {
        this.updateUserId = updateUserId == null ? null : updateUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_patient_dietary_history.UPDATE_DATETIME
     *
     * @return the value of tbl_patient_dietary_history.UPDATE_DATETIME
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public Date getUpdateDatetime() {
        return updateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_patient_dietary_history.UPDATE_DATETIME
     *
     * @param updateDatetime the value for tbl_patient_dietary_history.UPDATE_DATETIME
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public void setUpdateDatetime(Date updateDatetime) {
        this.updateDatetime = updateDatetime;
    }
}