package com.doerit.model.diagnostic;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class MedicalRecordExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tbl_patient_medical_record
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tbl_patient_medical_record
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tbl_patient_medical_record
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_patient_medical_record
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public MedicalRecordExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_patient_medical_record
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_patient_medical_record
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_patient_medical_record
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_patient_medical_record
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_patient_medical_record
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_patient_medical_record
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_patient_medical_record
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_patient_medical_record
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_patient_medical_record
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_patient_medical_record
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tbl_patient_medical_record
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("ID like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("ID not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andAllergyDrugIsNull() {
            addCriterion("ALLERGY_DRUG is null");
            return (Criteria) this;
        }

        public Criteria andAllergyDrugIsNotNull() {
            addCriterion("ALLERGY_DRUG is not null");
            return (Criteria) this;
        }

        public Criteria andAllergyDrugEqualTo(String value) {
            addCriterion("ALLERGY_DRUG =", value, "allergyDrug");
            return (Criteria) this;
        }

        public Criteria andAllergyDrugNotEqualTo(String value) {
            addCriterion("ALLERGY_DRUG <>", value, "allergyDrug");
            return (Criteria) this;
        }

        public Criteria andAllergyDrugGreaterThan(String value) {
            addCriterion("ALLERGY_DRUG >", value, "allergyDrug");
            return (Criteria) this;
        }

        public Criteria andAllergyDrugGreaterThanOrEqualTo(String value) {
            addCriterion("ALLERGY_DRUG >=", value, "allergyDrug");
            return (Criteria) this;
        }

        public Criteria andAllergyDrugLessThan(String value) {
            addCriterion("ALLERGY_DRUG <", value, "allergyDrug");
            return (Criteria) this;
        }

        public Criteria andAllergyDrugLessThanOrEqualTo(String value) {
            addCriterion("ALLERGY_DRUG <=", value, "allergyDrug");
            return (Criteria) this;
        }

        public Criteria andAllergyDrugLike(String value) {
            addCriterion("ALLERGY_DRUG like", value, "allergyDrug");
            return (Criteria) this;
        }

        public Criteria andAllergyDrugNotLike(String value) {
            addCriterion("ALLERGY_DRUG not like", value, "allergyDrug");
            return (Criteria) this;
        }

        public Criteria andAllergyDrugIn(List<String> values) {
            addCriterion("ALLERGY_DRUG in", values, "allergyDrug");
            return (Criteria) this;
        }

        public Criteria andAllergyDrugNotIn(List<String> values) {
            addCriterion("ALLERGY_DRUG not in", values, "allergyDrug");
            return (Criteria) this;
        }

        public Criteria andAllergyDrugBetween(String value1, String value2) {
            addCriterion("ALLERGY_DRUG between", value1, value2, "allergyDrug");
            return (Criteria) this;
        }

        public Criteria andAllergyDrugNotBetween(String value1, String value2) {
            addCriterion("ALLERGY_DRUG not between", value1, value2, "allergyDrug");
            return (Criteria) this;
        }

        public Criteria andAllergyFoodIsNull() {
            addCriterion("ALLERGY_FOOD is null");
            return (Criteria) this;
        }

        public Criteria andAllergyFoodIsNotNull() {
            addCriterion("ALLERGY_FOOD is not null");
            return (Criteria) this;
        }

        public Criteria andAllergyFoodEqualTo(String value) {
            addCriterion("ALLERGY_FOOD =", value, "allergyFood");
            return (Criteria) this;
        }

        public Criteria andAllergyFoodNotEqualTo(String value) {
            addCriterion("ALLERGY_FOOD <>", value, "allergyFood");
            return (Criteria) this;
        }

        public Criteria andAllergyFoodGreaterThan(String value) {
            addCriterion("ALLERGY_FOOD >", value, "allergyFood");
            return (Criteria) this;
        }

        public Criteria andAllergyFoodGreaterThanOrEqualTo(String value) {
            addCriterion("ALLERGY_FOOD >=", value, "allergyFood");
            return (Criteria) this;
        }

        public Criteria andAllergyFoodLessThan(String value) {
            addCriterion("ALLERGY_FOOD <", value, "allergyFood");
            return (Criteria) this;
        }

        public Criteria andAllergyFoodLessThanOrEqualTo(String value) {
            addCriterion("ALLERGY_FOOD <=", value, "allergyFood");
            return (Criteria) this;
        }

        public Criteria andAllergyFoodLike(String value) {
            addCriterion("ALLERGY_FOOD like", value, "allergyFood");
            return (Criteria) this;
        }

        public Criteria andAllergyFoodNotLike(String value) {
            addCriterion("ALLERGY_FOOD not like", value, "allergyFood");
            return (Criteria) this;
        }

        public Criteria andAllergyFoodIn(List<String> values) {
            addCriterion("ALLERGY_FOOD in", values, "allergyFood");
            return (Criteria) this;
        }

        public Criteria andAllergyFoodNotIn(List<String> values) {
            addCriterion("ALLERGY_FOOD not in", values, "allergyFood");
            return (Criteria) this;
        }

        public Criteria andAllergyFoodBetween(String value1, String value2) {
            addCriterion("ALLERGY_FOOD between", value1, value2, "allergyFood");
            return (Criteria) this;
        }

        public Criteria andAllergyFoodNotBetween(String value1, String value2) {
            addCriterion("ALLERGY_FOOD not between", value1, value2, "allergyFood");
            return (Criteria) this;
        }

        public Criteria andAllergyLatexIsNull() {
            addCriterion("ALLERGY_LATEX is null");
            return (Criteria) this;
        }

        public Criteria andAllergyLatexIsNotNull() {
            addCriterion("ALLERGY_LATEX is not null");
            return (Criteria) this;
        }

        public Criteria andAllergyLatexEqualTo(String value) {
            addCriterion("ALLERGY_LATEX =", value, "allergyLatex");
            return (Criteria) this;
        }

        public Criteria andAllergyLatexNotEqualTo(String value) {
            addCriterion("ALLERGY_LATEX <>", value, "allergyLatex");
            return (Criteria) this;
        }

        public Criteria andAllergyLatexGreaterThan(String value) {
            addCriterion("ALLERGY_LATEX >", value, "allergyLatex");
            return (Criteria) this;
        }

        public Criteria andAllergyLatexGreaterThanOrEqualTo(String value) {
            addCriterion("ALLERGY_LATEX >=", value, "allergyLatex");
            return (Criteria) this;
        }

        public Criteria andAllergyLatexLessThan(String value) {
            addCriterion("ALLERGY_LATEX <", value, "allergyLatex");
            return (Criteria) this;
        }

        public Criteria andAllergyLatexLessThanOrEqualTo(String value) {
            addCriterion("ALLERGY_LATEX <=", value, "allergyLatex");
            return (Criteria) this;
        }

        public Criteria andAllergyLatexLike(String value) {
            addCriterion("ALLERGY_LATEX like", value, "allergyLatex");
            return (Criteria) this;
        }

        public Criteria andAllergyLatexNotLike(String value) {
            addCriterion("ALLERGY_LATEX not like", value, "allergyLatex");
            return (Criteria) this;
        }

        public Criteria andAllergyLatexIn(List<String> values) {
            addCriterion("ALLERGY_LATEX in", values, "allergyLatex");
            return (Criteria) this;
        }

        public Criteria andAllergyLatexNotIn(List<String> values) {
            addCriterion("ALLERGY_LATEX not in", values, "allergyLatex");
            return (Criteria) this;
        }

        public Criteria andAllergyLatexBetween(String value1, String value2) {
            addCriterion("ALLERGY_LATEX between", value1, value2, "allergyLatex");
            return (Criteria) this;
        }

        public Criteria andAllergyLatexNotBetween(String value1, String value2) {
            addCriterion("ALLERGY_LATEX not between", value1, value2, "allergyLatex");
            return (Criteria) this;
        }

        public Criteria andAllergyOtherIsNull() {
            addCriterion("ALLERGY_OTHER is null");
            return (Criteria) this;
        }

        public Criteria andAllergyOtherIsNotNull() {
            addCriterion("ALLERGY_OTHER is not null");
            return (Criteria) this;
        }

        public Criteria andAllergyOtherEqualTo(String value) {
            addCriterion("ALLERGY_OTHER =", value, "allergyOther");
            return (Criteria) this;
        }

        public Criteria andAllergyOtherNotEqualTo(String value) {
            addCriterion("ALLERGY_OTHER <>", value, "allergyOther");
            return (Criteria) this;
        }

        public Criteria andAllergyOtherGreaterThan(String value) {
            addCriterion("ALLERGY_OTHER >", value, "allergyOther");
            return (Criteria) this;
        }

        public Criteria andAllergyOtherGreaterThanOrEqualTo(String value) {
            addCriterion("ALLERGY_OTHER >=", value, "allergyOther");
            return (Criteria) this;
        }

        public Criteria andAllergyOtherLessThan(String value) {
            addCriterion("ALLERGY_OTHER <", value, "allergyOther");
            return (Criteria) this;
        }

        public Criteria andAllergyOtherLessThanOrEqualTo(String value) {
            addCriterion("ALLERGY_OTHER <=", value, "allergyOther");
            return (Criteria) this;
        }

        public Criteria andAllergyOtherLike(String value) {
            addCriterion("ALLERGY_OTHER like", value, "allergyOther");
            return (Criteria) this;
        }

        public Criteria andAllergyOtherNotLike(String value) {
            addCriterion("ALLERGY_OTHER not like", value, "allergyOther");
            return (Criteria) this;
        }

        public Criteria andAllergyOtherIn(List<String> values) {
            addCriterion("ALLERGY_OTHER in", values, "allergyOther");
            return (Criteria) this;
        }

        public Criteria andAllergyOtherNotIn(List<String> values) {
            addCriterion("ALLERGY_OTHER not in", values, "allergyOther");
            return (Criteria) this;
        }

        public Criteria andAllergyOtherBetween(String value1, String value2) {
            addCriterion("ALLERGY_OTHER between", value1, value2, "allergyOther");
            return (Criteria) this;
        }

        public Criteria andAllergyOtherNotBetween(String value1, String value2) {
            addCriterion("ALLERGY_OTHER not between", value1, value2, "allergyOther");
            return (Criteria) this;
        }

        public Criteria andAnaemiaIsNull() {
            addCriterion("ANAEMIA is null");
            return (Criteria) this;
        }

        public Criteria andAnaemiaIsNotNull() {
            addCriterion("ANAEMIA is not null");
            return (Criteria) this;
        }

        public Criteria andAnaemiaEqualTo(Byte value) {
            addCriterion("ANAEMIA =", value, "anaemia");
            return (Criteria) this;
        }

        public Criteria andAnaemiaNotEqualTo(Byte value) {
            addCriterion("ANAEMIA <>", value, "anaemia");
            return (Criteria) this;
        }

        public Criteria andAnaemiaGreaterThan(Byte value) {
            addCriterion("ANAEMIA >", value, "anaemia");
            return (Criteria) this;
        }

        public Criteria andAnaemiaGreaterThanOrEqualTo(Byte value) {
            addCriterion("ANAEMIA >=", value, "anaemia");
            return (Criteria) this;
        }

        public Criteria andAnaemiaLessThan(Byte value) {
            addCriterion("ANAEMIA <", value, "anaemia");
            return (Criteria) this;
        }

        public Criteria andAnaemiaLessThanOrEqualTo(Byte value) {
            addCriterion("ANAEMIA <=", value, "anaemia");
            return (Criteria) this;
        }

        public Criteria andAnaemiaIn(List<Byte> values) {
            addCriterion("ANAEMIA in", values, "anaemia");
            return (Criteria) this;
        }

        public Criteria andAnaemiaNotIn(List<Byte> values) {
            addCriterion("ANAEMIA not in", values, "anaemia");
            return (Criteria) this;
        }

        public Criteria andAnaemiaBetween(Byte value1, Byte value2) {
            addCriterion("ANAEMIA between", value1, value2, "anaemia");
            return (Criteria) this;
        }

        public Criteria andAnaemiaNotBetween(Byte value1, Byte value2) {
            addCriterion("ANAEMIA not between", value1, value2, "anaemia");
            return (Criteria) this;
        }

        public Criteria andAsthmaIsNull() {
            addCriterion("ASTHMA is null");
            return (Criteria) this;
        }

        public Criteria andAsthmaIsNotNull() {
            addCriterion("ASTHMA is not null");
            return (Criteria) this;
        }

        public Criteria andAsthmaEqualTo(Byte value) {
            addCriterion("ASTHMA =", value, "asthma");
            return (Criteria) this;
        }

        public Criteria andAsthmaNotEqualTo(Byte value) {
            addCriterion("ASTHMA <>", value, "asthma");
            return (Criteria) this;
        }

        public Criteria andAsthmaGreaterThan(Byte value) {
            addCriterion("ASTHMA >", value, "asthma");
            return (Criteria) this;
        }

        public Criteria andAsthmaGreaterThanOrEqualTo(Byte value) {
            addCriterion("ASTHMA >=", value, "asthma");
            return (Criteria) this;
        }

        public Criteria andAsthmaLessThan(Byte value) {
            addCriterion("ASTHMA <", value, "asthma");
            return (Criteria) this;
        }

        public Criteria andAsthmaLessThanOrEqualTo(Byte value) {
            addCriterion("ASTHMA <=", value, "asthma");
            return (Criteria) this;
        }

        public Criteria andAsthmaIn(List<Byte> values) {
            addCriterion("ASTHMA in", values, "asthma");
            return (Criteria) this;
        }

        public Criteria andAsthmaNotIn(List<Byte> values) {
            addCriterion("ASTHMA not in", values, "asthma");
            return (Criteria) this;
        }

        public Criteria andAsthmaBetween(Byte value1, Byte value2) {
            addCriterion("ASTHMA between", value1, value2, "asthma");
            return (Criteria) this;
        }

        public Criteria andAsthmaNotBetween(Byte value1, Byte value2) {
            addCriterion("ASTHMA not between", value1, value2, "asthma");
            return (Criteria) this;
        }

        public Criteria andBleedingDisorderIsNull() {
            addCriterion("BLEEDING_DISORDER is null");
            return (Criteria) this;
        }

        public Criteria andBleedingDisorderIsNotNull() {
            addCriterion("BLEEDING_DISORDER is not null");
            return (Criteria) this;
        }

        public Criteria andBleedingDisorderEqualTo(String value) {
            addCriterion("BLEEDING_DISORDER =", value, "bleedingDisorder");
            return (Criteria) this;
        }

        public Criteria andBleedingDisorderNotEqualTo(String value) {
            addCriterion("BLEEDING_DISORDER <>", value, "bleedingDisorder");
            return (Criteria) this;
        }

        public Criteria andBleedingDisorderGreaterThan(String value) {
            addCriterion("BLEEDING_DISORDER >", value, "bleedingDisorder");
            return (Criteria) this;
        }

        public Criteria andBleedingDisorderGreaterThanOrEqualTo(String value) {
            addCriterion("BLEEDING_DISORDER >=", value, "bleedingDisorder");
            return (Criteria) this;
        }

        public Criteria andBleedingDisorderLessThan(String value) {
            addCriterion("BLEEDING_DISORDER <", value, "bleedingDisorder");
            return (Criteria) this;
        }

        public Criteria andBleedingDisorderLessThanOrEqualTo(String value) {
            addCriterion("BLEEDING_DISORDER <=", value, "bleedingDisorder");
            return (Criteria) this;
        }

        public Criteria andBleedingDisorderLike(String value) {
            addCriterion("BLEEDING_DISORDER like", value, "bleedingDisorder");
            return (Criteria) this;
        }

        public Criteria andBleedingDisorderNotLike(String value) {
            addCriterion("BLEEDING_DISORDER not like", value, "bleedingDisorder");
            return (Criteria) this;
        }

        public Criteria andBleedingDisorderIn(List<String> values) {
            addCriterion("BLEEDING_DISORDER in", values, "bleedingDisorder");
            return (Criteria) this;
        }

        public Criteria andBleedingDisorderNotIn(List<String> values) {
            addCriterion("BLEEDING_DISORDER not in", values, "bleedingDisorder");
            return (Criteria) this;
        }

        public Criteria andBleedingDisorderBetween(String value1, String value2) {
            addCriterion("BLEEDING_DISORDER between", value1, value2, "bleedingDisorder");
            return (Criteria) this;
        }

        public Criteria andBleedingDisorderNotBetween(String value1, String value2) {
            addCriterion("BLEEDING_DISORDER not between", value1, value2, "bleedingDisorder");
            return (Criteria) this;
        }

        public Criteria andCardiacDisordersIsNull() {
            addCriterion("CARDIAC_DISORDERS is null");
            return (Criteria) this;
        }

        public Criteria andCardiacDisordersIsNotNull() {
            addCriterion("CARDIAC_DISORDERS is not null");
            return (Criteria) this;
        }

        public Criteria andCardiacDisordersEqualTo(String value) {
            addCriterion("CARDIAC_DISORDERS =", value, "cardiacDisorders");
            return (Criteria) this;
        }

        public Criteria andCardiacDisordersNotEqualTo(String value) {
            addCriterion("CARDIAC_DISORDERS <>", value, "cardiacDisorders");
            return (Criteria) this;
        }

        public Criteria andCardiacDisordersGreaterThan(String value) {
            addCriterion("CARDIAC_DISORDERS >", value, "cardiacDisorders");
            return (Criteria) this;
        }

        public Criteria andCardiacDisordersGreaterThanOrEqualTo(String value) {
            addCriterion("CARDIAC_DISORDERS >=", value, "cardiacDisorders");
            return (Criteria) this;
        }

        public Criteria andCardiacDisordersLessThan(String value) {
            addCriterion("CARDIAC_DISORDERS <", value, "cardiacDisorders");
            return (Criteria) this;
        }

        public Criteria andCardiacDisordersLessThanOrEqualTo(String value) {
            addCriterion("CARDIAC_DISORDERS <=", value, "cardiacDisorders");
            return (Criteria) this;
        }

        public Criteria andCardiacDisordersLike(String value) {
            addCriterion("CARDIAC_DISORDERS like", value, "cardiacDisorders");
            return (Criteria) this;
        }

        public Criteria andCardiacDisordersNotLike(String value) {
            addCriterion("CARDIAC_DISORDERS not like", value, "cardiacDisorders");
            return (Criteria) this;
        }

        public Criteria andCardiacDisordersIn(List<String> values) {
            addCriterion("CARDIAC_DISORDERS in", values, "cardiacDisorders");
            return (Criteria) this;
        }

        public Criteria andCardiacDisordersNotIn(List<String> values) {
            addCriterion("CARDIAC_DISORDERS not in", values, "cardiacDisorders");
            return (Criteria) this;
        }

        public Criteria andCardiacDisordersBetween(String value1, String value2) {
            addCriterion("CARDIAC_DISORDERS between", value1, value2, "cardiacDisorders");
            return (Criteria) this;
        }

        public Criteria andCardiacDisordersNotBetween(String value1, String value2) {
            addCriterion("CARDIAC_DISORDERS not between", value1, value2, "cardiacDisorders");
            return (Criteria) this;
        }

        public Criteria andDevelopmentalIsNull() {
            addCriterion("DEVELOPMENTAL is null");
            return (Criteria) this;
        }

        public Criteria andDevelopmentalIsNotNull() {
            addCriterion("DEVELOPMENTAL is not null");
            return (Criteria) this;
        }

        public Criteria andDevelopmentalEqualTo(String value) {
            addCriterion("DEVELOPMENTAL =", value, "developmental");
            return (Criteria) this;
        }

        public Criteria andDevelopmentalNotEqualTo(String value) {
            addCriterion("DEVELOPMENTAL <>", value, "developmental");
            return (Criteria) this;
        }

        public Criteria andDevelopmentalGreaterThan(String value) {
            addCriterion("DEVELOPMENTAL >", value, "developmental");
            return (Criteria) this;
        }

        public Criteria andDevelopmentalGreaterThanOrEqualTo(String value) {
            addCriterion("DEVELOPMENTAL >=", value, "developmental");
            return (Criteria) this;
        }

        public Criteria andDevelopmentalLessThan(String value) {
            addCriterion("DEVELOPMENTAL <", value, "developmental");
            return (Criteria) this;
        }

        public Criteria andDevelopmentalLessThanOrEqualTo(String value) {
            addCriterion("DEVELOPMENTAL <=", value, "developmental");
            return (Criteria) this;
        }

        public Criteria andDevelopmentalLike(String value) {
            addCriterion("DEVELOPMENTAL like", value, "developmental");
            return (Criteria) this;
        }

        public Criteria andDevelopmentalNotLike(String value) {
            addCriterion("DEVELOPMENTAL not like", value, "developmental");
            return (Criteria) this;
        }

        public Criteria andDevelopmentalIn(List<String> values) {
            addCriterion("DEVELOPMENTAL in", values, "developmental");
            return (Criteria) this;
        }

        public Criteria andDevelopmentalNotIn(List<String> values) {
            addCriterion("DEVELOPMENTAL not in", values, "developmental");
            return (Criteria) this;
        }

        public Criteria andDevelopmentalBetween(String value1, String value2) {
            addCriterion("DEVELOPMENTAL between", value1, value2, "developmental");
            return (Criteria) this;
        }

        public Criteria andDevelopmentalNotBetween(String value1, String value2) {
            addCriterion("DEVELOPMENTAL not between", value1, value2, "developmental");
            return (Criteria) this;
        }

        public Criteria andEpilepsyIsNull() {
            addCriterion("EPILEPSY is null");
            return (Criteria) this;
        }

        public Criteria andEpilepsyIsNotNull() {
            addCriterion("EPILEPSY is not null");
            return (Criteria) this;
        }

        public Criteria andEpilepsyEqualTo(Byte value) {
            addCriterion("EPILEPSY =", value, "epilepsy");
            return (Criteria) this;
        }

        public Criteria andEpilepsyNotEqualTo(Byte value) {
            addCriterion("EPILEPSY <>", value, "epilepsy");
            return (Criteria) this;
        }

        public Criteria andEpilepsyGreaterThan(Byte value) {
            addCriterion("EPILEPSY >", value, "epilepsy");
            return (Criteria) this;
        }

        public Criteria andEpilepsyGreaterThanOrEqualTo(Byte value) {
            addCriterion("EPILEPSY >=", value, "epilepsy");
            return (Criteria) this;
        }

        public Criteria andEpilepsyLessThan(Byte value) {
            addCriterion("EPILEPSY <", value, "epilepsy");
            return (Criteria) this;
        }

        public Criteria andEpilepsyLessThanOrEqualTo(Byte value) {
            addCriterion("EPILEPSY <=", value, "epilepsy");
            return (Criteria) this;
        }

        public Criteria andEpilepsyIn(List<Byte> values) {
            addCriterion("EPILEPSY in", values, "epilepsy");
            return (Criteria) this;
        }

        public Criteria andEpilepsyNotIn(List<Byte> values) {
            addCriterion("EPILEPSY not in", values, "epilepsy");
            return (Criteria) this;
        }

        public Criteria andEpilepsyBetween(Byte value1, Byte value2) {
            addCriterion("EPILEPSY between", value1, value2, "epilepsy");
            return (Criteria) this;
        }

        public Criteria andEpilepsyNotBetween(Byte value1, Byte value2) {
            addCriterion("EPILEPSY not between", value1, value2, "epilepsy");
            return (Criteria) this;
        }

        public Criteria andEndocrineIsNull() {
            addCriterion("ENDOCRINE is null");
            return (Criteria) this;
        }

        public Criteria andEndocrineIsNotNull() {
            addCriterion("ENDOCRINE is not null");
            return (Criteria) this;
        }

        public Criteria andEndocrineEqualTo(String value) {
            addCriterion("ENDOCRINE =", value, "endocrine");
            return (Criteria) this;
        }

        public Criteria andEndocrineNotEqualTo(String value) {
            addCriterion("ENDOCRINE <>", value, "endocrine");
            return (Criteria) this;
        }

        public Criteria andEndocrineGreaterThan(String value) {
            addCriterion("ENDOCRINE >", value, "endocrine");
            return (Criteria) this;
        }

        public Criteria andEndocrineGreaterThanOrEqualTo(String value) {
            addCriterion("ENDOCRINE >=", value, "endocrine");
            return (Criteria) this;
        }

        public Criteria andEndocrineLessThan(String value) {
            addCriterion("ENDOCRINE <", value, "endocrine");
            return (Criteria) this;
        }

        public Criteria andEndocrineLessThanOrEqualTo(String value) {
            addCriterion("ENDOCRINE <=", value, "endocrine");
            return (Criteria) this;
        }

        public Criteria andEndocrineLike(String value) {
            addCriterion("ENDOCRINE like", value, "endocrine");
            return (Criteria) this;
        }

        public Criteria andEndocrineNotLike(String value) {
            addCriterion("ENDOCRINE not like", value, "endocrine");
            return (Criteria) this;
        }

        public Criteria andEndocrineIn(List<String> values) {
            addCriterion("ENDOCRINE in", values, "endocrine");
            return (Criteria) this;
        }

        public Criteria andEndocrineNotIn(List<String> values) {
            addCriterion("ENDOCRINE not in", values, "endocrine");
            return (Criteria) this;
        }

        public Criteria andEndocrineBetween(String value1, String value2) {
            addCriterion("ENDOCRINE between", value1, value2, "endocrine");
            return (Criteria) this;
        }

        public Criteria andEndocrineNotBetween(String value1, String value2) {
            addCriterion("ENDOCRINE not between", value1, value2, "endocrine");
            return (Criteria) this;
        }

        public Criteria andGastroIntestinalIsNull() {
            addCriterion("GASTRO_INTESTINAL is null");
            return (Criteria) this;
        }

        public Criteria andGastroIntestinalIsNotNull() {
            addCriterion("GASTRO_INTESTINAL is not null");
            return (Criteria) this;
        }

        public Criteria andGastroIntestinalEqualTo(String value) {
            addCriterion("GASTRO_INTESTINAL =", value, "gastroIntestinal");
            return (Criteria) this;
        }

        public Criteria andGastroIntestinalNotEqualTo(String value) {
            addCriterion("GASTRO_INTESTINAL <>", value, "gastroIntestinal");
            return (Criteria) this;
        }

        public Criteria andGastroIntestinalGreaterThan(String value) {
            addCriterion("GASTRO_INTESTINAL >", value, "gastroIntestinal");
            return (Criteria) this;
        }

        public Criteria andGastroIntestinalGreaterThanOrEqualTo(String value) {
            addCriterion("GASTRO_INTESTINAL >=", value, "gastroIntestinal");
            return (Criteria) this;
        }

        public Criteria andGastroIntestinalLessThan(String value) {
            addCriterion("GASTRO_INTESTINAL <", value, "gastroIntestinal");
            return (Criteria) this;
        }

        public Criteria andGastroIntestinalLessThanOrEqualTo(String value) {
            addCriterion("GASTRO_INTESTINAL <=", value, "gastroIntestinal");
            return (Criteria) this;
        }

        public Criteria andGastroIntestinalLike(String value) {
            addCriterion("GASTRO_INTESTINAL like", value, "gastroIntestinal");
            return (Criteria) this;
        }

        public Criteria andGastroIntestinalNotLike(String value) {
            addCriterion("GASTRO_INTESTINAL not like", value, "gastroIntestinal");
            return (Criteria) this;
        }

        public Criteria andGastroIntestinalIn(List<String> values) {
            addCriterion("GASTRO_INTESTINAL in", values, "gastroIntestinal");
            return (Criteria) this;
        }

        public Criteria andGastroIntestinalNotIn(List<String> values) {
            addCriterion("GASTRO_INTESTINAL not in", values, "gastroIntestinal");
            return (Criteria) this;
        }

        public Criteria andGastroIntestinalBetween(String value1, String value2) {
            addCriterion("GASTRO_INTESTINAL between", value1, value2, "gastroIntestinal");
            return (Criteria) this;
        }

        public Criteria andGastroIntestinalNotBetween(String value1, String value2) {
            addCriterion("GASTRO_INTESTINAL not between", value1, value2, "gastroIntestinal");
            return (Criteria) this;
        }

        public Criteria andHepatitisIsNull() {
            addCriterion("HEPATITIS is null");
            return (Criteria) this;
        }

        public Criteria andHepatitisIsNotNull() {
            addCriterion("HEPATITIS is not null");
            return (Criteria) this;
        }

        public Criteria andHepatitisEqualTo(String value) {
            addCriterion("HEPATITIS =", value, "hepatitis");
            return (Criteria) this;
        }

        public Criteria andHepatitisNotEqualTo(String value) {
            addCriterion("HEPATITIS <>", value, "hepatitis");
            return (Criteria) this;
        }

        public Criteria andHepatitisGreaterThan(String value) {
            addCriterion("HEPATITIS >", value, "hepatitis");
            return (Criteria) this;
        }

        public Criteria andHepatitisGreaterThanOrEqualTo(String value) {
            addCriterion("HEPATITIS >=", value, "hepatitis");
            return (Criteria) this;
        }

        public Criteria andHepatitisLessThan(String value) {
            addCriterion("HEPATITIS <", value, "hepatitis");
            return (Criteria) this;
        }

        public Criteria andHepatitisLessThanOrEqualTo(String value) {
            addCriterion("HEPATITIS <=", value, "hepatitis");
            return (Criteria) this;
        }

        public Criteria andHepatitisLike(String value) {
            addCriterion("HEPATITIS like", value, "hepatitis");
            return (Criteria) this;
        }

        public Criteria andHepatitisNotLike(String value) {
            addCriterion("HEPATITIS not like", value, "hepatitis");
            return (Criteria) this;
        }

        public Criteria andHepatitisIn(List<String> values) {
            addCriterion("HEPATITIS in", values, "hepatitis");
            return (Criteria) this;
        }

        public Criteria andHepatitisNotIn(List<String> values) {
            addCriterion("HEPATITIS not in", values, "hepatitis");
            return (Criteria) this;
        }

        public Criteria andHepatitisBetween(String value1, String value2) {
            addCriterion("HEPATITIS between", value1, value2, "hepatitis");
            return (Criteria) this;
        }

        public Criteria andHepatitisNotBetween(String value1, String value2) {
            addCriterion("HEPATITIS not between", value1, value2, "hepatitis");
            return (Criteria) this;
        }

        public Criteria andHivIsNull() {
            addCriterion("HIV is null");
            return (Criteria) this;
        }

        public Criteria andHivIsNotNull() {
            addCriterion("HIV is not null");
            return (Criteria) this;
        }

        public Criteria andHivEqualTo(Byte value) {
            addCriterion("HIV =", value, "hiv");
            return (Criteria) this;
        }

        public Criteria andHivNotEqualTo(Byte value) {
            addCriterion("HIV <>", value, "hiv");
            return (Criteria) this;
        }

        public Criteria andHivGreaterThan(Byte value) {
            addCriterion("HIV >", value, "hiv");
            return (Criteria) this;
        }

        public Criteria andHivGreaterThanOrEqualTo(Byte value) {
            addCriterion("HIV >=", value, "hiv");
            return (Criteria) this;
        }

        public Criteria andHivLessThan(Byte value) {
            addCriterion("HIV <", value, "hiv");
            return (Criteria) this;
        }

        public Criteria andHivLessThanOrEqualTo(Byte value) {
            addCriterion("HIV <=", value, "hiv");
            return (Criteria) this;
        }

        public Criteria andHivIn(List<Byte> values) {
            addCriterion("HIV in", values, "hiv");
            return (Criteria) this;
        }

        public Criteria andHivNotIn(List<Byte> values) {
            addCriterion("HIV not in", values, "hiv");
            return (Criteria) this;
        }

        public Criteria andHivBetween(Byte value1, Byte value2) {
            addCriterion("HIV between", value1, value2, "hiv");
            return (Criteria) this;
        }

        public Criteria andHivNotBetween(Byte value1, Byte value2) {
            addCriterion("HIV not between", value1, value2, "hiv");
            return (Criteria) this;
        }

        public Criteria andHypertensionIsNull() {
            addCriterion("HYPERTENSION is null");
            return (Criteria) this;
        }

        public Criteria andHypertensionIsNotNull() {
            addCriterion("HYPERTENSION is not null");
            return (Criteria) this;
        }

        public Criteria andHypertensionEqualTo(Byte value) {
            addCriterion("HYPERTENSION =", value, "hypertension");
            return (Criteria) this;
        }

        public Criteria andHypertensionNotEqualTo(Byte value) {
            addCriterion("HYPERTENSION <>", value, "hypertension");
            return (Criteria) this;
        }

        public Criteria andHypertensionGreaterThan(Byte value) {
            addCriterion("HYPERTENSION >", value, "hypertension");
            return (Criteria) this;
        }

        public Criteria andHypertensionGreaterThanOrEqualTo(Byte value) {
            addCriterion("HYPERTENSION >=", value, "hypertension");
            return (Criteria) this;
        }

        public Criteria andHypertensionLessThan(Byte value) {
            addCriterion("HYPERTENSION <", value, "hypertension");
            return (Criteria) this;
        }

        public Criteria andHypertensionLessThanOrEqualTo(Byte value) {
            addCriterion("HYPERTENSION <=", value, "hypertension");
            return (Criteria) this;
        }

        public Criteria andHypertensionIn(List<Byte> values) {
            addCriterion("HYPERTENSION in", values, "hypertension");
            return (Criteria) this;
        }

        public Criteria andHypertensionNotIn(List<Byte> values) {
            addCriterion("HYPERTENSION not in", values, "hypertension");
            return (Criteria) this;
        }

        public Criteria andHypertensionBetween(Byte value1, Byte value2) {
            addCriterion("HYPERTENSION between", value1, value2, "hypertension");
            return (Criteria) this;
        }

        public Criteria andHypertensionNotBetween(Byte value1, Byte value2) {
            addCriterion("HYPERTENSION not between", value1, value2, "hypertension");
            return (Criteria) this;
        }

        public Criteria andLiverDisorderIsNull() {
            addCriterion("LIVER_DISORDER is null");
            return (Criteria) this;
        }

        public Criteria andLiverDisorderIsNotNull() {
            addCriterion("LIVER_DISORDER is not null");
            return (Criteria) this;
        }

        public Criteria andLiverDisorderEqualTo(Byte value) {
            addCriterion("LIVER_DISORDER =", value, "liverDisorder");
            return (Criteria) this;
        }

        public Criteria andLiverDisorderNotEqualTo(Byte value) {
            addCriterion("LIVER_DISORDER <>", value, "liverDisorder");
            return (Criteria) this;
        }

        public Criteria andLiverDisorderGreaterThan(Byte value) {
            addCriterion("LIVER_DISORDER >", value, "liverDisorder");
            return (Criteria) this;
        }

        public Criteria andLiverDisorderGreaterThanOrEqualTo(Byte value) {
            addCriterion("LIVER_DISORDER >=", value, "liverDisorder");
            return (Criteria) this;
        }

        public Criteria andLiverDisorderLessThan(Byte value) {
            addCriterion("LIVER_DISORDER <", value, "liverDisorder");
            return (Criteria) this;
        }

        public Criteria andLiverDisorderLessThanOrEqualTo(Byte value) {
            addCriterion("LIVER_DISORDER <=", value, "liverDisorder");
            return (Criteria) this;
        }

        public Criteria andLiverDisorderIn(List<Byte> values) {
            addCriterion("LIVER_DISORDER in", values, "liverDisorder");
            return (Criteria) this;
        }

        public Criteria andLiverDisorderNotIn(List<Byte> values) {
            addCriterion("LIVER_DISORDER not in", values, "liverDisorder");
            return (Criteria) this;
        }

        public Criteria andLiverDisorderBetween(Byte value1, Byte value2) {
            addCriterion("LIVER_DISORDER between", value1, value2, "liverDisorder");
            return (Criteria) this;
        }

        public Criteria andLiverDisorderNotBetween(Byte value1, Byte value2) {
            addCriterion("LIVER_DISORDER not between", value1, value2, "liverDisorder");
            return (Criteria) this;
        }

        public Criteria andMusculoSkeletalIsNull() {
            addCriterion("MUSCULO_SKELETAL is null");
            return (Criteria) this;
        }

        public Criteria andMusculoSkeletalIsNotNull() {
            addCriterion("MUSCULO_SKELETAL is not null");
            return (Criteria) this;
        }

        public Criteria andMusculoSkeletalEqualTo(String value) {
            addCriterion("MUSCULO_SKELETAL =", value, "musculoSkeletal");
            return (Criteria) this;
        }

        public Criteria andMusculoSkeletalNotEqualTo(String value) {
            addCriterion("MUSCULO_SKELETAL <>", value, "musculoSkeletal");
            return (Criteria) this;
        }

        public Criteria andMusculoSkeletalGreaterThan(String value) {
            addCriterion("MUSCULO_SKELETAL >", value, "musculoSkeletal");
            return (Criteria) this;
        }

        public Criteria andMusculoSkeletalGreaterThanOrEqualTo(String value) {
            addCriterion("MUSCULO_SKELETAL >=", value, "musculoSkeletal");
            return (Criteria) this;
        }

        public Criteria andMusculoSkeletalLessThan(String value) {
            addCriterion("MUSCULO_SKELETAL <", value, "musculoSkeletal");
            return (Criteria) this;
        }

        public Criteria andMusculoSkeletalLessThanOrEqualTo(String value) {
            addCriterion("MUSCULO_SKELETAL <=", value, "musculoSkeletal");
            return (Criteria) this;
        }

        public Criteria andMusculoSkeletalLike(String value) {
            addCriterion("MUSCULO_SKELETAL like", value, "musculoSkeletal");
            return (Criteria) this;
        }

        public Criteria andMusculoSkeletalNotLike(String value) {
            addCriterion("MUSCULO_SKELETAL not like", value, "musculoSkeletal");
            return (Criteria) this;
        }

        public Criteria andMusculoSkeletalIn(List<String> values) {
            addCriterion("MUSCULO_SKELETAL in", values, "musculoSkeletal");
            return (Criteria) this;
        }

        public Criteria andMusculoSkeletalNotIn(List<String> values) {
            addCriterion("MUSCULO_SKELETAL not in", values, "musculoSkeletal");
            return (Criteria) this;
        }

        public Criteria andMusculoSkeletalBetween(String value1, String value2) {
            addCriterion("MUSCULO_SKELETAL between", value1, value2, "musculoSkeletal");
            return (Criteria) this;
        }

        public Criteria andMusculoSkeletalNotBetween(String value1, String value2) {
            addCriterion("MUSCULO_SKELETAL not between", value1, value2, "musculoSkeletal");
            return (Criteria) this;
        }

        public Criteria andNeurologicalDisorderIsNull() {
            addCriterion("NEUROLOGICAL_DISORDER is null");
            return (Criteria) this;
        }

        public Criteria andNeurologicalDisorderIsNotNull() {
            addCriterion("NEUROLOGICAL_DISORDER is not null");
            return (Criteria) this;
        }

        public Criteria andNeurologicalDisorderEqualTo(String value) {
            addCriterion("NEUROLOGICAL_DISORDER =", value, "neurologicalDisorder");
            return (Criteria) this;
        }

        public Criteria andNeurologicalDisorderNotEqualTo(String value) {
            addCriterion("NEUROLOGICAL_DISORDER <>", value, "neurologicalDisorder");
            return (Criteria) this;
        }

        public Criteria andNeurologicalDisorderGreaterThan(String value) {
            addCriterion("NEUROLOGICAL_DISORDER >", value, "neurologicalDisorder");
            return (Criteria) this;
        }

        public Criteria andNeurologicalDisorderGreaterThanOrEqualTo(String value) {
            addCriterion("NEUROLOGICAL_DISORDER >=", value, "neurologicalDisorder");
            return (Criteria) this;
        }

        public Criteria andNeurologicalDisorderLessThan(String value) {
            addCriterion("NEUROLOGICAL_DISORDER <", value, "neurologicalDisorder");
            return (Criteria) this;
        }

        public Criteria andNeurologicalDisorderLessThanOrEqualTo(String value) {
            addCriterion("NEUROLOGICAL_DISORDER <=", value, "neurologicalDisorder");
            return (Criteria) this;
        }

        public Criteria andNeurologicalDisorderLike(String value) {
            addCriterion("NEUROLOGICAL_DISORDER like", value, "neurologicalDisorder");
            return (Criteria) this;
        }

        public Criteria andNeurologicalDisorderNotLike(String value) {
            addCriterion("NEUROLOGICAL_DISORDER not like", value, "neurologicalDisorder");
            return (Criteria) this;
        }

        public Criteria andNeurologicalDisorderIn(List<String> values) {
            addCriterion("NEUROLOGICAL_DISORDER in", values, "neurologicalDisorder");
            return (Criteria) this;
        }

        public Criteria andNeurologicalDisorderNotIn(List<String> values) {
            addCriterion("NEUROLOGICAL_DISORDER not in", values, "neurologicalDisorder");
            return (Criteria) this;
        }

        public Criteria andNeurologicalDisorderBetween(String value1, String value2) {
            addCriterion("NEUROLOGICAL_DISORDER between", value1, value2, "neurologicalDisorder");
            return (Criteria) this;
        }

        public Criteria andNeurologicalDisorderNotBetween(String value1, String value2) {
            addCriterion("NEUROLOGICAL_DISORDER not between", value1, value2, "neurologicalDisorder");
            return (Criteria) this;
        }

        public Criteria andBehavioralDisorderIsNull() {
            addCriterion("BEHAVIORAL_DISORDER is null");
            return (Criteria) this;
        }

        public Criteria andBehavioralDisorderIsNotNull() {
            addCriterion("BEHAVIORAL_DISORDER is not null");
            return (Criteria) this;
        }

        public Criteria andBehavioralDisorderEqualTo(String value) {
            addCriterion("BEHAVIORAL_DISORDER =", value, "behavioralDisorder");
            return (Criteria) this;
        }

        public Criteria andBehavioralDisorderNotEqualTo(String value) {
            addCriterion("BEHAVIORAL_DISORDER <>", value, "behavioralDisorder");
            return (Criteria) this;
        }

        public Criteria andBehavioralDisorderGreaterThan(String value) {
            addCriterion("BEHAVIORAL_DISORDER >", value, "behavioralDisorder");
            return (Criteria) this;
        }

        public Criteria andBehavioralDisorderGreaterThanOrEqualTo(String value) {
            addCriterion("BEHAVIORAL_DISORDER >=", value, "behavioralDisorder");
            return (Criteria) this;
        }

        public Criteria andBehavioralDisorderLessThan(String value) {
            addCriterion("BEHAVIORAL_DISORDER <", value, "behavioralDisorder");
            return (Criteria) this;
        }

        public Criteria andBehavioralDisorderLessThanOrEqualTo(String value) {
            addCriterion("BEHAVIORAL_DISORDER <=", value, "behavioralDisorder");
            return (Criteria) this;
        }

        public Criteria andBehavioralDisorderLike(String value) {
            addCriterion("BEHAVIORAL_DISORDER like", value, "behavioralDisorder");
            return (Criteria) this;
        }

        public Criteria andBehavioralDisorderNotLike(String value) {
            addCriterion("BEHAVIORAL_DISORDER not like", value, "behavioralDisorder");
            return (Criteria) this;
        }

        public Criteria andBehavioralDisorderIn(List<String> values) {
            addCriterion("BEHAVIORAL_DISORDER in", values, "behavioralDisorder");
            return (Criteria) this;
        }

        public Criteria andBehavioralDisorderNotIn(List<String> values) {
            addCriterion("BEHAVIORAL_DISORDER not in", values, "behavioralDisorder");
            return (Criteria) this;
        }

        public Criteria andBehavioralDisorderBetween(String value1, String value2) {
            addCriterion("BEHAVIORAL_DISORDER between", value1, value2, "behavioralDisorder");
            return (Criteria) this;
        }

        public Criteria andBehavioralDisorderNotBetween(String value1, String value2) {
            addCriterion("BEHAVIORAL_DISORDER not between", value1, value2, "behavioralDisorder");
            return (Criteria) this;
        }

        public Criteria andTmdIsNull() {
            addCriterion("TMD is null");
            return (Criteria) this;
        }

        public Criteria andTmdIsNotNull() {
            addCriterion("TMD is not null");
            return (Criteria) this;
        }

        public Criteria andTmdEqualTo(String value) {
            addCriterion("TMD =", value, "tmd");
            return (Criteria) this;
        }

        public Criteria andTmdNotEqualTo(String value) {
            addCriterion("TMD <>", value, "tmd");
            return (Criteria) this;
        }

        public Criteria andTmdGreaterThan(String value) {
            addCriterion("TMD >", value, "tmd");
            return (Criteria) this;
        }

        public Criteria andTmdGreaterThanOrEqualTo(String value) {
            addCriterion("TMD >=", value, "tmd");
            return (Criteria) this;
        }

        public Criteria andTmdLessThan(String value) {
            addCriterion("TMD <", value, "tmd");
            return (Criteria) this;
        }

        public Criteria andTmdLessThanOrEqualTo(String value) {
            addCriterion("TMD <=", value, "tmd");
            return (Criteria) this;
        }

        public Criteria andTmdLike(String value) {
            addCriterion("TMD like", value, "tmd");
            return (Criteria) this;
        }

        public Criteria andTmdNotLike(String value) {
            addCriterion("TMD not like", value, "tmd");
            return (Criteria) this;
        }

        public Criteria andTmdIn(List<String> values) {
            addCriterion("TMD in", values, "tmd");
            return (Criteria) this;
        }

        public Criteria andTmdNotIn(List<String> values) {
            addCriterion("TMD not in", values, "tmd");
            return (Criteria) this;
        }

        public Criteria andTmdBetween(String value1, String value2) {
            addCriterion("TMD between", value1, value2, "tmd");
            return (Criteria) this;
        }

        public Criteria andTmdNotBetween(String value1, String value2) {
            addCriterion("TMD not between", value1, value2, "tmd");
            return (Criteria) this;
        }

        public Criteria andRenalDisorderIsNull() {
            addCriterion("RENAL_DISORDER is null");
            return (Criteria) this;
        }

        public Criteria andRenalDisorderIsNotNull() {
            addCriterion("RENAL_DISORDER is not null");
            return (Criteria) this;
        }

        public Criteria andRenalDisorderEqualTo(String value) {
            addCriterion("RENAL_DISORDER =", value, "renalDisorder");
            return (Criteria) this;
        }

        public Criteria andRenalDisorderNotEqualTo(String value) {
            addCriterion("RENAL_DISORDER <>", value, "renalDisorder");
            return (Criteria) this;
        }

        public Criteria andRenalDisorderGreaterThan(String value) {
            addCriterion("RENAL_DISORDER >", value, "renalDisorder");
            return (Criteria) this;
        }

        public Criteria andRenalDisorderGreaterThanOrEqualTo(String value) {
            addCriterion("RENAL_DISORDER >=", value, "renalDisorder");
            return (Criteria) this;
        }

        public Criteria andRenalDisorderLessThan(String value) {
            addCriterion("RENAL_DISORDER <", value, "renalDisorder");
            return (Criteria) this;
        }

        public Criteria andRenalDisorderLessThanOrEqualTo(String value) {
            addCriterion("RENAL_DISORDER <=", value, "renalDisorder");
            return (Criteria) this;
        }

        public Criteria andRenalDisorderLike(String value) {
            addCriterion("RENAL_DISORDER like", value, "renalDisorder");
            return (Criteria) this;
        }

        public Criteria andRenalDisorderNotLike(String value) {
            addCriterion("RENAL_DISORDER not like", value, "renalDisorder");
            return (Criteria) this;
        }

        public Criteria andRenalDisorderIn(List<String> values) {
            addCriterion("RENAL_DISORDER in", values, "renalDisorder");
            return (Criteria) this;
        }

        public Criteria andRenalDisorderNotIn(List<String> values) {
            addCriterion("RENAL_DISORDER not in", values, "renalDisorder");
            return (Criteria) this;
        }

        public Criteria andRenalDisorderBetween(String value1, String value2) {
            addCriterion("RENAL_DISORDER between", value1, value2, "renalDisorder");
            return (Criteria) this;
        }

        public Criteria andRenalDisorderNotBetween(String value1, String value2) {
            addCriterion("RENAL_DISORDER not between", value1, value2, "renalDisorder");
            return (Criteria) this;
        }

        public Criteria andOtherDisordersIsNull() {
            addCriterion("OTHER_DISORDERS is null");
            return (Criteria) this;
        }

        public Criteria andOtherDisordersIsNotNull() {
            addCriterion("OTHER_DISORDERS is not null");
            return (Criteria) this;
        }

        public Criteria andOtherDisordersEqualTo(String value) {
            addCriterion("OTHER_DISORDERS =", value, "otherDisorders");
            return (Criteria) this;
        }

        public Criteria andOtherDisordersNotEqualTo(String value) {
            addCriterion("OTHER_DISORDERS <>", value, "otherDisorders");
            return (Criteria) this;
        }

        public Criteria andOtherDisordersGreaterThan(String value) {
            addCriterion("OTHER_DISORDERS >", value, "otherDisorders");
            return (Criteria) this;
        }

        public Criteria andOtherDisordersGreaterThanOrEqualTo(String value) {
            addCriterion("OTHER_DISORDERS >=", value, "otherDisorders");
            return (Criteria) this;
        }

        public Criteria andOtherDisordersLessThan(String value) {
            addCriterion("OTHER_DISORDERS <", value, "otherDisorders");
            return (Criteria) this;
        }

        public Criteria andOtherDisordersLessThanOrEqualTo(String value) {
            addCriterion("OTHER_DISORDERS <=", value, "otherDisorders");
            return (Criteria) this;
        }

        public Criteria andOtherDisordersLike(String value) {
            addCriterion("OTHER_DISORDERS like", value, "otherDisorders");
            return (Criteria) this;
        }

        public Criteria andOtherDisordersNotLike(String value) {
            addCriterion("OTHER_DISORDERS not like", value, "otherDisorders");
            return (Criteria) this;
        }

        public Criteria andOtherDisordersIn(List<String> values) {
            addCriterion("OTHER_DISORDERS in", values, "otherDisorders");
            return (Criteria) this;
        }

        public Criteria andOtherDisordersNotIn(List<String> values) {
            addCriterion("OTHER_DISORDERS not in", values, "otherDisorders");
            return (Criteria) this;
        }

        public Criteria andOtherDisordersBetween(String value1, String value2) {
            addCriterion("OTHER_DISORDERS between", value1, value2, "otherDisorders");
            return (Criteria) this;
        }

        public Criteria andOtherDisordersNotBetween(String value1, String value2) {
            addCriterion("OTHER_DISORDERS not between", value1, value2, "otherDisorders");
            return (Criteria) this;
        }

        public Criteria andPregnancyIsNull() {
            addCriterion("PREGNANCY is null");
            return (Criteria) this;
        }

        public Criteria andPregnancyIsNotNull() {
            addCriterion("PREGNANCY is not null");
            return (Criteria) this;
        }

        public Criteria andPregnancyEqualTo(String value) {
            addCriterion("PREGNANCY =", value, "pregnancy");
            return (Criteria) this;
        }

        public Criteria andPregnancyNotEqualTo(String value) {
            addCriterion("PREGNANCY <>", value, "pregnancy");
            return (Criteria) this;
        }

        public Criteria andPregnancyGreaterThan(String value) {
            addCriterion("PREGNANCY >", value, "pregnancy");
            return (Criteria) this;
        }

        public Criteria andPregnancyGreaterThanOrEqualTo(String value) {
            addCriterion("PREGNANCY >=", value, "pregnancy");
            return (Criteria) this;
        }

        public Criteria andPregnancyLessThan(String value) {
            addCriterion("PREGNANCY <", value, "pregnancy");
            return (Criteria) this;
        }

        public Criteria andPregnancyLessThanOrEqualTo(String value) {
            addCriterion("PREGNANCY <=", value, "pregnancy");
            return (Criteria) this;
        }

        public Criteria andPregnancyLike(String value) {
            addCriterion("PREGNANCY like", value, "pregnancy");
            return (Criteria) this;
        }

        public Criteria andPregnancyNotLike(String value) {
            addCriterion("PREGNANCY not like", value, "pregnancy");
            return (Criteria) this;
        }

        public Criteria andPregnancyIn(List<String> values) {
            addCriterion("PREGNANCY in", values, "pregnancy");
            return (Criteria) this;
        }

        public Criteria andPregnancyNotIn(List<String> values) {
            addCriterion("PREGNANCY not in", values, "pregnancy");
            return (Criteria) this;
        }

        public Criteria andPregnancyBetween(String value1, String value2) {
            addCriterion("PREGNANCY between", value1, value2, "pregnancy");
            return (Criteria) this;
        }

        public Criteria andPregnancyNotBetween(String value1, String value2) {
            addCriterion("PREGNANCY not between", value1, value2, "pregnancy");
            return (Criteria) this;
        }

        public Criteria andCommentIsNull() {
            addCriterion("COMMENT is null");
            return (Criteria) this;
        }

        public Criteria andCommentIsNotNull() {
            addCriterion("COMMENT is not null");
            return (Criteria) this;
        }

        public Criteria andCommentEqualTo(String value) {
            addCriterion("COMMENT =", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentNotEqualTo(String value) {
            addCriterion("COMMENT <>", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentGreaterThan(String value) {
            addCriterion("COMMENT >", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentGreaterThanOrEqualTo(String value) {
            addCriterion("COMMENT >=", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentLessThan(String value) {
            addCriterion("COMMENT <", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentLessThanOrEqualTo(String value) {
            addCriterion("COMMENT <=", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentLike(String value) {
            addCriterion("COMMENT like", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentNotLike(String value) {
            addCriterion("COMMENT not like", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentIn(List<String> values) {
            addCriterion("COMMENT in", values, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentNotIn(List<String> values) {
            addCriterion("COMMENT not in", values, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentBetween(String value1, String value2) {
            addCriterion("COMMENT between", value1, value2, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentNotBetween(String value1, String value2) {
            addCriterion("COMMENT not between", value1, value2, "comment");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("STATUS is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Byte value) {
            addCriterion("STATUS =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Byte value) {
            addCriterion("STATUS <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Byte value) {
            addCriterion("STATUS >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Byte value) {
            addCriterion("STATUS >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Byte value) {
            addCriterion("STATUS <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Byte value) {
            addCriterion("STATUS <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Byte> values) {
            addCriterion("STATUS in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Byte> values) {
            addCriterion("STATUS not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Byte value1, Byte value2) {
            addCriterion("STATUS between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Byte value1, Byte value2) {
            addCriterion("STATUS not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andSortOrderIsNull() {
            addCriterion("SORT_ORDER is null");
            return (Criteria) this;
        }

        public Criteria andSortOrderIsNotNull() {
            addCriterion("SORT_ORDER is not null");
            return (Criteria) this;
        }

        public Criteria andSortOrderEqualTo(Integer value) {
            addCriterion("SORT_ORDER =", value, "sortOrder");
            return (Criteria) this;
        }

        public Criteria andSortOrderNotEqualTo(Integer value) {
            addCriterion("SORT_ORDER <>", value, "sortOrder");
            return (Criteria) this;
        }

        public Criteria andSortOrderGreaterThan(Integer value) {
            addCriterion("SORT_ORDER >", value, "sortOrder");
            return (Criteria) this;
        }

        public Criteria andSortOrderGreaterThanOrEqualTo(Integer value) {
            addCriterion("SORT_ORDER >=", value, "sortOrder");
            return (Criteria) this;
        }

        public Criteria andSortOrderLessThan(Integer value) {
            addCriterion("SORT_ORDER <", value, "sortOrder");
            return (Criteria) this;
        }

        public Criteria andSortOrderLessThanOrEqualTo(Integer value) {
            addCriterion("SORT_ORDER <=", value, "sortOrder");
            return (Criteria) this;
        }

        public Criteria andSortOrderIn(List<Integer> values) {
            addCriterion("SORT_ORDER in", values, "sortOrder");
            return (Criteria) this;
        }

        public Criteria andSortOrderNotIn(List<Integer> values) {
            addCriterion("SORT_ORDER not in", values, "sortOrder");
            return (Criteria) this;
        }

        public Criteria andSortOrderBetween(Integer value1, Integer value2) {
            addCriterion("SORT_ORDER between", value1, value2, "sortOrder");
            return (Criteria) this;
        }

        public Criteria andSortOrderNotBetween(Integer value1, Integer value2) {
            addCriterion("SORT_ORDER not between", value1, value2, "sortOrder");
            return (Criteria) this;
        }

        public Criteria andInsertUserIdIsNull() {
            addCriterion("INSERT_USER_ID is null");
            return (Criteria) this;
        }

        public Criteria andInsertUserIdIsNotNull() {
            addCriterion("INSERT_USER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andInsertUserIdEqualTo(String value) {
            addCriterion("INSERT_USER_ID =", value, "insertUserId");
            return (Criteria) this;
        }

        public Criteria andInsertUserIdNotEqualTo(String value) {
            addCriterion("INSERT_USER_ID <>", value, "insertUserId");
            return (Criteria) this;
        }

        public Criteria andInsertUserIdGreaterThan(String value) {
            addCriterion("INSERT_USER_ID >", value, "insertUserId");
            return (Criteria) this;
        }

        public Criteria andInsertUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("INSERT_USER_ID >=", value, "insertUserId");
            return (Criteria) this;
        }

        public Criteria andInsertUserIdLessThan(String value) {
            addCriterion("INSERT_USER_ID <", value, "insertUserId");
            return (Criteria) this;
        }

        public Criteria andInsertUserIdLessThanOrEqualTo(String value) {
            addCriterion("INSERT_USER_ID <=", value, "insertUserId");
            return (Criteria) this;
        }

        public Criteria andInsertUserIdLike(String value) {
            addCriterion("INSERT_USER_ID like", value, "insertUserId");
            return (Criteria) this;
        }

        public Criteria andInsertUserIdNotLike(String value) {
            addCriterion("INSERT_USER_ID not like", value, "insertUserId");
            return (Criteria) this;
        }

        public Criteria andInsertUserIdIn(List<String> values) {
            addCriterion("INSERT_USER_ID in", values, "insertUserId");
            return (Criteria) this;
        }

        public Criteria andInsertUserIdNotIn(List<String> values) {
            addCriterion("INSERT_USER_ID not in", values, "insertUserId");
            return (Criteria) this;
        }

        public Criteria andInsertUserIdBetween(String value1, String value2) {
            addCriterion("INSERT_USER_ID between", value1, value2, "insertUserId");
            return (Criteria) this;
        }

        public Criteria andInsertUserIdNotBetween(String value1, String value2) {
            addCriterion("INSERT_USER_ID not between", value1, value2, "insertUserId");
            return (Criteria) this;
        }

        public Criteria andInsertDatetimeIsNull() {
            addCriterion("INSERT_DATETIME is null");
            return (Criteria) this;
        }

        public Criteria andInsertDatetimeIsNotNull() {
            addCriterion("INSERT_DATETIME is not null");
            return (Criteria) this;
        }

        public Criteria andInsertDatetimeEqualTo(Date value) {
            addCriterion("INSERT_DATETIME =", value, "insertDatetime");
            return (Criteria) this;
        }

        public Criteria andInsertDatetimeNotEqualTo(Date value) {
            addCriterion("INSERT_DATETIME <>", value, "insertDatetime");
            return (Criteria) this;
        }

        public Criteria andInsertDatetimeGreaterThan(Date value) {
            addCriterion("INSERT_DATETIME >", value, "insertDatetime");
            return (Criteria) this;
        }

        public Criteria andInsertDatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("INSERT_DATETIME >=", value, "insertDatetime");
            return (Criteria) this;
        }

        public Criteria andInsertDatetimeLessThan(Date value) {
            addCriterion("INSERT_DATETIME <", value, "insertDatetime");
            return (Criteria) this;
        }

        public Criteria andInsertDatetimeLessThanOrEqualTo(Date value) {
            addCriterion("INSERT_DATETIME <=", value, "insertDatetime");
            return (Criteria) this;
        }

        public Criteria andInsertDatetimeIn(List<Date> values) {
            addCriterion("INSERT_DATETIME in", values, "insertDatetime");
            return (Criteria) this;
        }

        public Criteria andInsertDatetimeNotIn(List<Date> values) {
            addCriterion("INSERT_DATETIME not in", values, "insertDatetime");
            return (Criteria) this;
        }

        public Criteria andInsertDatetimeBetween(Date value1, Date value2) {
            addCriterion("INSERT_DATETIME between", value1, value2, "insertDatetime");
            return (Criteria) this;
        }

        public Criteria andInsertDatetimeNotBetween(Date value1, Date value2) {
            addCriterion("INSERT_DATETIME not between", value1, value2, "insertDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdIsNull() {
            addCriterion("UPDATE_USER_ID is null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdIsNotNull() {
            addCriterion("UPDATE_USER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdEqualTo(String value) {
            addCriterion("UPDATE_USER_ID =", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotEqualTo(String value) {
            addCriterion("UPDATE_USER_ID <>", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdGreaterThan(String value) {
            addCriterion("UPDATE_USER_ID >", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("UPDATE_USER_ID >=", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdLessThan(String value) {
            addCriterion("UPDATE_USER_ID <", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdLessThanOrEqualTo(String value) {
            addCriterion("UPDATE_USER_ID <=", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdLike(String value) {
            addCriterion("UPDATE_USER_ID like", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotLike(String value) {
            addCriterion("UPDATE_USER_ID not like", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdIn(List<String> values) {
            addCriterion("UPDATE_USER_ID in", values, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotIn(List<String> values) {
            addCriterion("UPDATE_USER_ID not in", values, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdBetween(String value1, String value2) {
            addCriterion("UPDATE_USER_ID between", value1, value2, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotBetween(String value1, String value2) {
            addCriterion("UPDATE_USER_ID not between", value1, value2, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeIsNull() {
            addCriterion("UPDATE_DATETIME is null");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeIsNotNull() {
            addCriterion("UPDATE_DATETIME is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeEqualTo(Date value) {
            addCriterion("UPDATE_DATETIME =", value, "updateDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeNotEqualTo(Date value) {
            addCriterion("UPDATE_DATETIME <>", value, "updateDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeGreaterThan(Date value) {
            addCriterion("UPDATE_DATETIME >", value, "updateDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("UPDATE_DATETIME >=", value, "updateDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeLessThan(Date value) {
            addCriterion("UPDATE_DATETIME <", value, "updateDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeLessThanOrEqualTo(Date value) {
            addCriterion("UPDATE_DATETIME <=", value, "updateDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeIn(List<Date> values) {
            addCriterion("UPDATE_DATETIME in", values, "updateDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeNotIn(List<Date> values) {
            addCriterion("UPDATE_DATETIME not in", values, "updateDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeBetween(Date value1, Date value2) {
            addCriterion("UPDATE_DATETIME between", value1, value2, "updateDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeNotBetween(Date value1, Date value2) {
            addCriterion("UPDATE_DATETIME not between", value1, value2, "updateDatetime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tbl_patient_medical_record
     *
     * @mbg.generated do_not_delete_during_merge Tue Dec 19 03:23:32 IST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tbl_patient_medical_record
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }
    }
}