package com.doerit.model.diagnostic;

import java.util.Date;

public class MedicalRecord {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_patient_medical_record.ID
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_patient_medical_record.ALLERGY_DRUG
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    private String allergyDrug;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_patient_medical_record.ALLERGY_FOOD
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    private String allergyFood;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_patient_medical_record.ALLERGY_LATEX
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    private String allergyLatex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_patient_medical_record.ALLERGY_OTHER
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    private String allergyOther;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_patient_medical_record.ANAEMIA
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    private Byte anaemia;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_patient_medical_record.ASTHMA
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    private Byte asthma;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_patient_medical_record.BLEEDING_DISORDER
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    private String bleedingDisorder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_patient_medical_record.CARDIAC_DISORDERS
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    private String cardiacDisorders;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_patient_medical_record.DEVELOPMENTAL
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    private String developmental;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_patient_medical_record.EPILEPSY
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    private Byte epilepsy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_patient_medical_record.ENDOCRINE
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    private String endocrine;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_patient_medical_record.GASTRO_INTESTINAL
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    private String gastroIntestinal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_patient_medical_record.HEPATITIS
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    private String hepatitis;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_patient_medical_record.HIV
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    private Byte hiv;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_patient_medical_record.HYPERTENSION
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    private Byte hypertension;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_patient_medical_record.LIVER_DISORDER
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    private Byte liverDisorder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_patient_medical_record.MUSCULO_SKELETAL
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    private String musculoSkeletal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_patient_medical_record.NEUROLOGICAL_DISORDER
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    private String neurologicalDisorder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_patient_medical_record.BEHAVIORAL_DISORDER
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    private String behavioralDisorder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_patient_medical_record.TMD
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    private String tmd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_patient_medical_record.RENAL_DISORDER
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    private String renalDisorder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_patient_medical_record.OTHER_DISORDERS
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    private String otherDisorders;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_patient_medical_record.PREGNANCY
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    private String pregnancy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_patient_medical_record.COMMENT
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    private String comment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_patient_medical_record.STATUS
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_patient_medical_record.SORT_ORDER
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    private Integer sortOrder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_patient_medical_record.INSERT_USER_ID
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    private String insertUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_patient_medical_record.INSERT_DATETIME
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    private Date insertDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_patient_medical_record.UPDATE_USER_ID
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    private String updateUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_patient_medical_record.UPDATE_DATETIME
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    private Date updateDatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_patient_medical_record.ID
     *
     * @return the value of tbl_patient_medical_record.ID
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_patient_medical_record.ID
     *
     * @param id the value for tbl_patient_medical_record.ID
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_patient_medical_record.ALLERGY_DRUG
     *
     * @return the value of tbl_patient_medical_record.ALLERGY_DRUG
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public String getAllergyDrug() {
        return allergyDrug;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_patient_medical_record.ALLERGY_DRUG
     *
     * @param allergyDrug the value for tbl_patient_medical_record.ALLERGY_DRUG
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public void setAllergyDrug(String allergyDrug) {
        this.allergyDrug = allergyDrug == null ? null : allergyDrug.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_patient_medical_record.ALLERGY_FOOD
     *
     * @return the value of tbl_patient_medical_record.ALLERGY_FOOD
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public String getAllergyFood() {
        return allergyFood;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_patient_medical_record.ALLERGY_FOOD
     *
     * @param allergyFood the value for tbl_patient_medical_record.ALLERGY_FOOD
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public void setAllergyFood(String allergyFood) {
        this.allergyFood = allergyFood == null ? null : allergyFood.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_patient_medical_record.ALLERGY_LATEX
     *
     * @return the value of tbl_patient_medical_record.ALLERGY_LATEX
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public String getAllergyLatex() {
        return allergyLatex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_patient_medical_record.ALLERGY_LATEX
     *
     * @param allergyLatex the value for tbl_patient_medical_record.ALLERGY_LATEX
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public void setAllergyLatex(String allergyLatex) {
        this.allergyLatex = allergyLatex == null ? null : allergyLatex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_patient_medical_record.ALLERGY_OTHER
     *
     * @return the value of tbl_patient_medical_record.ALLERGY_OTHER
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public String getAllergyOther() {
        return allergyOther;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_patient_medical_record.ALLERGY_OTHER
     *
     * @param allergyOther the value for tbl_patient_medical_record.ALLERGY_OTHER
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public void setAllergyOther(String allergyOther) {
        this.allergyOther = allergyOther == null ? null : allergyOther.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_patient_medical_record.ANAEMIA
     *
     * @return the value of tbl_patient_medical_record.ANAEMIA
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public Byte getAnaemia() {
        return anaemia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_patient_medical_record.ANAEMIA
     *
     * @param anaemia the value for tbl_patient_medical_record.ANAEMIA
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public void setAnaemia(Byte anaemia) {
        this.anaemia = anaemia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_patient_medical_record.ASTHMA
     *
     * @return the value of tbl_patient_medical_record.ASTHMA
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public Byte getAsthma() {
        return asthma;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_patient_medical_record.ASTHMA
     *
     * @param asthma the value for tbl_patient_medical_record.ASTHMA
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public void setAsthma(Byte asthma) {
        this.asthma = asthma;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_patient_medical_record.BLEEDING_DISORDER
     *
     * @return the value of tbl_patient_medical_record.BLEEDING_DISORDER
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public String getBleedingDisorder() {
        return bleedingDisorder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_patient_medical_record.BLEEDING_DISORDER
     *
     * @param bleedingDisorder the value for tbl_patient_medical_record.BLEEDING_DISORDER
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public void setBleedingDisorder(String bleedingDisorder) {
        this.bleedingDisorder = bleedingDisorder == null ? null : bleedingDisorder.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_patient_medical_record.CARDIAC_DISORDERS
     *
     * @return the value of tbl_patient_medical_record.CARDIAC_DISORDERS
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public String getCardiacDisorders() {
        return cardiacDisorders;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_patient_medical_record.CARDIAC_DISORDERS
     *
     * @param cardiacDisorders the value for tbl_patient_medical_record.CARDIAC_DISORDERS
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public void setCardiacDisorders(String cardiacDisorders) {
        this.cardiacDisorders = cardiacDisorders == null ? null : cardiacDisorders.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_patient_medical_record.DEVELOPMENTAL
     *
     * @return the value of tbl_patient_medical_record.DEVELOPMENTAL
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public String getDevelopmental() {
        return developmental;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_patient_medical_record.DEVELOPMENTAL
     *
     * @param developmental the value for tbl_patient_medical_record.DEVELOPMENTAL
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public void setDevelopmental(String developmental) {
        this.developmental = developmental == null ? null : developmental.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_patient_medical_record.EPILEPSY
     *
     * @return the value of tbl_patient_medical_record.EPILEPSY
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public Byte getEpilepsy() {
        return epilepsy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_patient_medical_record.EPILEPSY
     *
     * @param epilepsy the value for tbl_patient_medical_record.EPILEPSY
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public void setEpilepsy(Byte epilepsy) {
        this.epilepsy = epilepsy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_patient_medical_record.ENDOCRINE
     *
     * @return the value of tbl_patient_medical_record.ENDOCRINE
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public String getEndocrine() {
        return endocrine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_patient_medical_record.ENDOCRINE
     *
     * @param endocrine the value for tbl_patient_medical_record.ENDOCRINE
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public void setEndocrine(String endocrine) {
        this.endocrine = endocrine == null ? null : endocrine.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_patient_medical_record.GASTRO_INTESTINAL
     *
     * @return the value of tbl_patient_medical_record.GASTRO_INTESTINAL
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public String getGastroIntestinal() {
        return gastroIntestinal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_patient_medical_record.GASTRO_INTESTINAL
     *
     * @param gastroIntestinal the value for tbl_patient_medical_record.GASTRO_INTESTINAL
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public void setGastroIntestinal(String gastroIntestinal) {
        this.gastroIntestinal = gastroIntestinal == null ? null : gastroIntestinal.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_patient_medical_record.HEPATITIS
     *
     * @return the value of tbl_patient_medical_record.HEPATITIS
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public String getHepatitis() {
        return hepatitis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_patient_medical_record.HEPATITIS
     *
     * @param hepatitis the value for tbl_patient_medical_record.HEPATITIS
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public void setHepatitis(String hepatitis) {
        this.hepatitis = hepatitis == null ? null : hepatitis.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_patient_medical_record.HIV
     *
     * @return the value of tbl_patient_medical_record.HIV
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public Byte getHiv() {
        return hiv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_patient_medical_record.HIV
     *
     * @param hiv the value for tbl_patient_medical_record.HIV
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public void setHiv(Byte hiv) {
        this.hiv = hiv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_patient_medical_record.HYPERTENSION
     *
     * @return the value of tbl_patient_medical_record.HYPERTENSION
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public Byte getHypertension() {
        return hypertension;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_patient_medical_record.HYPERTENSION
     *
     * @param hypertension the value for tbl_patient_medical_record.HYPERTENSION
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public void setHypertension(Byte hypertension) {
        this.hypertension = hypertension;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_patient_medical_record.LIVER_DISORDER
     *
     * @return the value of tbl_patient_medical_record.LIVER_DISORDER
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public Byte getLiverDisorder() {
        return liverDisorder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_patient_medical_record.LIVER_DISORDER
     *
     * @param liverDisorder the value for tbl_patient_medical_record.LIVER_DISORDER
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public void setLiverDisorder(Byte liverDisorder) {
        this.liverDisorder = liverDisorder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_patient_medical_record.MUSCULO_SKELETAL
     *
     * @return the value of tbl_patient_medical_record.MUSCULO_SKELETAL
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public String getMusculoSkeletal() {
        return musculoSkeletal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_patient_medical_record.MUSCULO_SKELETAL
     *
     * @param musculoSkeletal the value for tbl_patient_medical_record.MUSCULO_SKELETAL
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public void setMusculoSkeletal(String musculoSkeletal) {
        this.musculoSkeletal = musculoSkeletal == null ? null : musculoSkeletal.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_patient_medical_record.NEUROLOGICAL_DISORDER
     *
     * @return the value of tbl_patient_medical_record.NEUROLOGICAL_DISORDER
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public String getNeurologicalDisorder() {
        return neurologicalDisorder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_patient_medical_record.NEUROLOGICAL_DISORDER
     *
     * @param neurologicalDisorder the value for tbl_patient_medical_record.NEUROLOGICAL_DISORDER
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public void setNeurologicalDisorder(String neurologicalDisorder) {
        this.neurologicalDisorder = neurologicalDisorder == null ? null : neurologicalDisorder.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_patient_medical_record.BEHAVIORAL_DISORDER
     *
     * @return the value of tbl_patient_medical_record.BEHAVIORAL_DISORDER
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public String getBehavioralDisorder() {
        return behavioralDisorder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_patient_medical_record.BEHAVIORAL_DISORDER
     *
     * @param behavioralDisorder the value for tbl_patient_medical_record.BEHAVIORAL_DISORDER
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public void setBehavioralDisorder(String behavioralDisorder) {
        this.behavioralDisorder = behavioralDisorder == null ? null : behavioralDisorder.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_patient_medical_record.TMD
     *
     * @return the value of tbl_patient_medical_record.TMD
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public String getTmd() {
        return tmd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_patient_medical_record.TMD
     *
     * @param tmd the value for tbl_patient_medical_record.TMD
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public void setTmd(String tmd) {
        this.tmd = tmd == null ? null : tmd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_patient_medical_record.RENAL_DISORDER
     *
     * @return the value of tbl_patient_medical_record.RENAL_DISORDER
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public String getRenalDisorder() {
        return renalDisorder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_patient_medical_record.RENAL_DISORDER
     *
     * @param renalDisorder the value for tbl_patient_medical_record.RENAL_DISORDER
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public void setRenalDisorder(String renalDisorder) {
        this.renalDisorder = renalDisorder == null ? null : renalDisorder.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_patient_medical_record.OTHER_DISORDERS
     *
     * @return the value of tbl_patient_medical_record.OTHER_DISORDERS
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public String getOtherDisorders() {
        return otherDisorders;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_patient_medical_record.OTHER_DISORDERS
     *
     * @param otherDisorders the value for tbl_patient_medical_record.OTHER_DISORDERS
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public void setOtherDisorders(String otherDisorders) {
        this.otherDisorders = otherDisorders == null ? null : otherDisorders.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_patient_medical_record.PREGNANCY
     *
     * @return the value of tbl_patient_medical_record.PREGNANCY
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public String getPregnancy() {
        return pregnancy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_patient_medical_record.PREGNANCY
     *
     * @param pregnancy the value for tbl_patient_medical_record.PREGNANCY
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public void setPregnancy(String pregnancy) {
        this.pregnancy = pregnancy == null ? null : pregnancy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_patient_medical_record.COMMENT
     *
     * @return the value of tbl_patient_medical_record.COMMENT
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_patient_medical_record.COMMENT
     *
     * @param comment the value for tbl_patient_medical_record.COMMENT
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_patient_medical_record.STATUS
     *
     * @return the value of tbl_patient_medical_record.STATUS
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_patient_medical_record.STATUS
     *
     * @param status the value for tbl_patient_medical_record.STATUS
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_patient_medical_record.SORT_ORDER
     *
     * @return the value of tbl_patient_medical_record.SORT_ORDER
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public Integer getSortOrder() {
        return sortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_patient_medical_record.SORT_ORDER
     *
     * @param sortOrder the value for tbl_patient_medical_record.SORT_ORDER
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public void setSortOrder(Integer sortOrder) {
        this.sortOrder = sortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_patient_medical_record.INSERT_USER_ID
     *
     * @return the value of tbl_patient_medical_record.INSERT_USER_ID
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public String getInsertUserId() {
        return insertUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_patient_medical_record.INSERT_USER_ID
     *
     * @param insertUserId the value for tbl_patient_medical_record.INSERT_USER_ID
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public void setInsertUserId(String insertUserId) {
        this.insertUserId = insertUserId == null ? null : insertUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_patient_medical_record.INSERT_DATETIME
     *
     * @return the value of tbl_patient_medical_record.INSERT_DATETIME
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public Date getInsertDatetime() {
        return insertDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_patient_medical_record.INSERT_DATETIME
     *
     * @param insertDatetime the value for tbl_patient_medical_record.INSERT_DATETIME
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public void setInsertDatetime(Date insertDatetime) {
        this.insertDatetime = insertDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_patient_medical_record.UPDATE_USER_ID
     *
     * @return the value of tbl_patient_medical_record.UPDATE_USER_ID
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public String getUpdateUserId() {
        return updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_patient_medical_record.UPDATE_USER_ID
     *
     * @param updateUserId the value for tbl_patient_medical_record.UPDATE_USER_ID
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public void setUpdateUserId(String updateUserId) {
        this.updateUserId = updateUserId == null ? null : updateUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_patient_medical_record.UPDATE_DATETIME
     *
     * @return the value of tbl_patient_medical_record.UPDATE_DATETIME
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public Date getUpdateDatetime() {
        return updateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_patient_medical_record.UPDATE_DATETIME
     *
     * @param updateDatetime the value for tbl_patient_medical_record.UPDATE_DATETIME
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public void setUpdateDatetime(Date updateDatetime) {
        this.updateDatetime = updateDatetime;
    }
}