package com.doerit.model.diagnostic;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class PastDentalHistoryExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tbl_patient_past_dental_history
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tbl_patient_past_dental_history
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tbl_patient_past_dental_history
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_patient_past_dental_history
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public PastDentalHistoryExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_patient_past_dental_history
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_patient_past_dental_history
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_patient_past_dental_history
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_patient_past_dental_history
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_patient_past_dental_history
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_patient_past_dental_history
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_patient_past_dental_history
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_patient_past_dental_history
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_patient_past_dental_history
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_patient_past_dental_history
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tbl_patient_past_dental_history
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("ID like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("ID not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andExtractionStatusIsNull() {
            addCriterion("EXTRACTION_STATUS is null");
            return (Criteria) this;
        }

        public Criteria andExtractionStatusIsNotNull() {
            addCriterion("EXTRACTION_STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andExtractionStatusEqualTo(Byte value) {
            addCriterion("EXTRACTION_STATUS =", value, "extractionStatus");
            return (Criteria) this;
        }

        public Criteria andExtractionStatusNotEqualTo(Byte value) {
            addCriterion("EXTRACTION_STATUS <>", value, "extractionStatus");
            return (Criteria) this;
        }

        public Criteria andExtractionStatusGreaterThan(Byte value) {
            addCriterion("EXTRACTION_STATUS >", value, "extractionStatus");
            return (Criteria) this;
        }

        public Criteria andExtractionStatusGreaterThanOrEqualTo(Byte value) {
            addCriterion("EXTRACTION_STATUS >=", value, "extractionStatus");
            return (Criteria) this;
        }

        public Criteria andExtractionStatusLessThan(Byte value) {
            addCriterion("EXTRACTION_STATUS <", value, "extractionStatus");
            return (Criteria) this;
        }

        public Criteria andExtractionStatusLessThanOrEqualTo(Byte value) {
            addCriterion("EXTRACTION_STATUS <=", value, "extractionStatus");
            return (Criteria) this;
        }

        public Criteria andExtractionStatusIn(List<Byte> values) {
            addCriterion("EXTRACTION_STATUS in", values, "extractionStatus");
            return (Criteria) this;
        }

        public Criteria andExtractionStatusNotIn(List<Byte> values) {
            addCriterion("EXTRACTION_STATUS not in", values, "extractionStatus");
            return (Criteria) this;
        }

        public Criteria andExtractionStatusBetween(Byte value1, Byte value2) {
            addCriterion("EXTRACTION_STATUS between", value1, value2, "extractionStatus");
            return (Criteria) this;
        }

        public Criteria andExtractionStatusNotBetween(Byte value1, Byte value2) {
            addCriterion("EXTRACTION_STATUS not between", value1, value2, "extractionStatus");
            return (Criteria) this;
        }

        public Criteria andExtractionComplicationsIsNull() {
            addCriterion("EXTRACTION_COMPLICATIONS is null");
            return (Criteria) this;
        }

        public Criteria andExtractionComplicationsIsNotNull() {
            addCriterion("EXTRACTION_COMPLICATIONS is not null");
            return (Criteria) this;
        }

        public Criteria andExtractionComplicationsEqualTo(Byte value) {
            addCriterion("EXTRACTION_COMPLICATIONS =", value, "extractionComplications");
            return (Criteria) this;
        }

        public Criteria andExtractionComplicationsNotEqualTo(Byte value) {
            addCriterion("EXTRACTION_COMPLICATIONS <>", value, "extractionComplications");
            return (Criteria) this;
        }

        public Criteria andExtractionComplicationsGreaterThan(Byte value) {
            addCriterion("EXTRACTION_COMPLICATIONS >", value, "extractionComplications");
            return (Criteria) this;
        }

        public Criteria andExtractionComplicationsGreaterThanOrEqualTo(Byte value) {
            addCriterion("EXTRACTION_COMPLICATIONS >=", value, "extractionComplications");
            return (Criteria) this;
        }

        public Criteria andExtractionComplicationsLessThan(Byte value) {
            addCriterion("EXTRACTION_COMPLICATIONS <", value, "extractionComplications");
            return (Criteria) this;
        }

        public Criteria andExtractionComplicationsLessThanOrEqualTo(Byte value) {
            addCriterion("EXTRACTION_COMPLICATIONS <=", value, "extractionComplications");
            return (Criteria) this;
        }

        public Criteria andExtractionComplicationsIn(List<Byte> values) {
            addCriterion("EXTRACTION_COMPLICATIONS in", values, "extractionComplications");
            return (Criteria) this;
        }

        public Criteria andExtractionComplicationsNotIn(List<Byte> values) {
            addCriterion("EXTRACTION_COMPLICATIONS not in", values, "extractionComplications");
            return (Criteria) this;
        }

        public Criteria andExtractionComplicationsBetween(Byte value1, Byte value2) {
            addCriterion("EXTRACTION_COMPLICATIONS between", value1, value2, "extractionComplications");
            return (Criteria) this;
        }

        public Criteria andExtractionComplicationsNotBetween(Byte value1, Byte value2) {
            addCriterion("EXTRACTION_COMPLICATIONS not between", value1, value2, "extractionComplications");
            return (Criteria) this;
        }

        public Criteria andOtherSurgeryIsNull() {
            addCriterion("OTHER_SURGERY is null");
            return (Criteria) this;
        }

        public Criteria andOtherSurgeryIsNotNull() {
            addCriterion("OTHER_SURGERY is not null");
            return (Criteria) this;
        }

        public Criteria andOtherSurgeryEqualTo(Byte value) {
            addCriterion("OTHER_SURGERY =", value, "otherSurgery");
            return (Criteria) this;
        }

        public Criteria andOtherSurgeryNotEqualTo(Byte value) {
            addCriterion("OTHER_SURGERY <>", value, "otherSurgery");
            return (Criteria) this;
        }

        public Criteria andOtherSurgeryGreaterThan(Byte value) {
            addCriterion("OTHER_SURGERY >", value, "otherSurgery");
            return (Criteria) this;
        }

        public Criteria andOtherSurgeryGreaterThanOrEqualTo(Byte value) {
            addCriterion("OTHER_SURGERY >=", value, "otherSurgery");
            return (Criteria) this;
        }

        public Criteria andOtherSurgeryLessThan(Byte value) {
            addCriterion("OTHER_SURGERY <", value, "otherSurgery");
            return (Criteria) this;
        }

        public Criteria andOtherSurgeryLessThanOrEqualTo(Byte value) {
            addCriterion("OTHER_SURGERY <=", value, "otherSurgery");
            return (Criteria) this;
        }

        public Criteria andOtherSurgeryIn(List<Byte> values) {
            addCriterion("OTHER_SURGERY in", values, "otherSurgery");
            return (Criteria) this;
        }

        public Criteria andOtherSurgeryNotIn(List<Byte> values) {
            addCriterion("OTHER_SURGERY not in", values, "otherSurgery");
            return (Criteria) this;
        }

        public Criteria andOtherSurgeryBetween(Byte value1, Byte value2) {
            addCriterion("OTHER_SURGERY between", value1, value2, "otherSurgery");
            return (Criteria) this;
        }

        public Criteria andOtherSurgeryNotBetween(Byte value1, Byte value2) {
            addCriterion("OTHER_SURGERY not between", value1, value2, "otherSurgery");
            return (Criteria) this;
        }

        public Criteria andPeriodontalRxIsNull() {
            addCriterion("PERIODONTAL_RX is null");
            return (Criteria) this;
        }

        public Criteria andPeriodontalRxIsNotNull() {
            addCriterion("PERIODONTAL_RX is not null");
            return (Criteria) this;
        }

        public Criteria andPeriodontalRxEqualTo(String value) {
            addCriterion("PERIODONTAL_RX =", value, "periodontalRx");
            return (Criteria) this;
        }

        public Criteria andPeriodontalRxNotEqualTo(String value) {
            addCriterion("PERIODONTAL_RX <>", value, "periodontalRx");
            return (Criteria) this;
        }

        public Criteria andPeriodontalRxGreaterThan(String value) {
            addCriterion("PERIODONTAL_RX >", value, "periodontalRx");
            return (Criteria) this;
        }

        public Criteria andPeriodontalRxGreaterThanOrEqualTo(String value) {
            addCriterion("PERIODONTAL_RX >=", value, "periodontalRx");
            return (Criteria) this;
        }

        public Criteria andPeriodontalRxLessThan(String value) {
            addCriterion("PERIODONTAL_RX <", value, "periodontalRx");
            return (Criteria) this;
        }

        public Criteria andPeriodontalRxLessThanOrEqualTo(String value) {
            addCriterion("PERIODONTAL_RX <=", value, "periodontalRx");
            return (Criteria) this;
        }

        public Criteria andPeriodontalRxLike(String value) {
            addCriterion("PERIODONTAL_RX like", value, "periodontalRx");
            return (Criteria) this;
        }

        public Criteria andPeriodontalRxNotLike(String value) {
            addCriterion("PERIODONTAL_RX not like", value, "periodontalRx");
            return (Criteria) this;
        }

        public Criteria andPeriodontalRxIn(List<String> values) {
            addCriterion("PERIODONTAL_RX in", values, "periodontalRx");
            return (Criteria) this;
        }

        public Criteria andPeriodontalRxNotIn(List<String> values) {
            addCriterion("PERIODONTAL_RX not in", values, "periodontalRx");
            return (Criteria) this;
        }

        public Criteria andPeriodontalRxBetween(String value1, String value2) {
            addCriterion("PERIODONTAL_RX between", value1, value2, "periodontalRx");
            return (Criteria) this;
        }

        public Criteria andPeriodontalRxNotBetween(String value1, String value2) {
            addCriterion("PERIODONTAL_RX not between", value1, value2, "periodontalRx");
            return (Criteria) this;
        }

        public Criteria andOrthodonticTreatmentStatusIsNull() {
            addCriterion("ORTHODONTIC_TREATMENT_STATUS is null");
            return (Criteria) this;
        }

        public Criteria andOrthodonticTreatmentStatusIsNotNull() {
            addCriterion("ORTHODONTIC_TREATMENT_STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andOrthodonticTreatmentStatusEqualTo(Byte value) {
            addCriterion("ORTHODONTIC_TREATMENT_STATUS =", value, "orthodonticTreatmentStatus");
            return (Criteria) this;
        }

        public Criteria andOrthodonticTreatmentStatusNotEqualTo(Byte value) {
            addCriterion("ORTHODONTIC_TREATMENT_STATUS <>", value, "orthodonticTreatmentStatus");
            return (Criteria) this;
        }

        public Criteria andOrthodonticTreatmentStatusGreaterThan(Byte value) {
            addCriterion("ORTHODONTIC_TREATMENT_STATUS >", value, "orthodonticTreatmentStatus");
            return (Criteria) this;
        }

        public Criteria andOrthodonticTreatmentStatusGreaterThanOrEqualTo(Byte value) {
            addCriterion("ORTHODONTIC_TREATMENT_STATUS >=", value, "orthodonticTreatmentStatus");
            return (Criteria) this;
        }

        public Criteria andOrthodonticTreatmentStatusLessThan(Byte value) {
            addCriterion("ORTHODONTIC_TREATMENT_STATUS <", value, "orthodonticTreatmentStatus");
            return (Criteria) this;
        }

        public Criteria andOrthodonticTreatmentStatusLessThanOrEqualTo(Byte value) {
            addCriterion("ORTHODONTIC_TREATMENT_STATUS <=", value, "orthodonticTreatmentStatus");
            return (Criteria) this;
        }

        public Criteria andOrthodonticTreatmentStatusIn(List<Byte> values) {
            addCriterion("ORTHODONTIC_TREATMENT_STATUS in", values, "orthodonticTreatmentStatus");
            return (Criteria) this;
        }

        public Criteria andOrthodonticTreatmentStatusNotIn(List<Byte> values) {
            addCriterion("ORTHODONTIC_TREATMENT_STATUS not in", values, "orthodonticTreatmentStatus");
            return (Criteria) this;
        }

        public Criteria andOrthodonticTreatmentStatusBetween(Byte value1, Byte value2) {
            addCriterion("ORTHODONTIC_TREATMENT_STATUS between", value1, value2, "orthodonticTreatmentStatus");
            return (Criteria) this;
        }

        public Criteria andOrthodonticTreatmentStatusNotBetween(Byte value1, Byte value2) {
            addCriterion("ORTHODONTIC_TREATMENT_STATUS not between", value1, value2, "orthodonticTreatmentStatus");
            return (Criteria) this;
        }

        public Criteria andOrthodonticTreatmentComplicationsIsNull() {
            addCriterion("ORTHODONTIC_TREATMENT_COMPLICATIONS is null");
            return (Criteria) this;
        }

        public Criteria andOrthodonticTreatmentComplicationsIsNotNull() {
            addCriterion("ORTHODONTIC_TREATMENT_COMPLICATIONS is not null");
            return (Criteria) this;
        }

        public Criteria andOrthodonticTreatmentComplicationsEqualTo(String value) {
            addCriterion("ORTHODONTIC_TREATMENT_COMPLICATIONS =", value, "orthodonticTreatmentComplications");
            return (Criteria) this;
        }

        public Criteria andOrthodonticTreatmentComplicationsNotEqualTo(String value) {
            addCriterion("ORTHODONTIC_TREATMENT_COMPLICATIONS <>", value, "orthodonticTreatmentComplications");
            return (Criteria) this;
        }

        public Criteria andOrthodonticTreatmentComplicationsGreaterThan(String value) {
            addCriterion("ORTHODONTIC_TREATMENT_COMPLICATIONS >", value, "orthodonticTreatmentComplications");
            return (Criteria) this;
        }

        public Criteria andOrthodonticTreatmentComplicationsGreaterThanOrEqualTo(String value) {
            addCriterion("ORTHODONTIC_TREATMENT_COMPLICATIONS >=", value, "orthodonticTreatmentComplications");
            return (Criteria) this;
        }

        public Criteria andOrthodonticTreatmentComplicationsLessThan(String value) {
            addCriterion("ORTHODONTIC_TREATMENT_COMPLICATIONS <", value, "orthodonticTreatmentComplications");
            return (Criteria) this;
        }

        public Criteria andOrthodonticTreatmentComplicationsLessThanOrEqualTo(String value) {
            addCriterion("ORTHODONTIC_TREATMENT_COMPLICATIONS <=", value, "orthodonticTreatmentComplications");
            return (Criteria) this;
        }

        public Criteria andOrthodonticTreatmentComplicationsLike(String value) {
            addCriterion("ORTHODONTIC_TREATMENT_COMPLICATIONS like", value, "orthodonticTreatmentComplications");
            return (Criteria) this;
        }

        public Criteria andOrthodonticTreatmentComplicationsNotLike(String value) {
            addCriterion("ORTHODONTIC_TREATMENT_COMPLICATIONS not like", value, "orthodonticTreatmentComplications");
            return (Criteria) this;
        }

        public Criteria andOrthodonticTreatmentComplicationsIn(List<String> values) {
            addCriterion("ORTHODONTIC_TREATMENT_COMPLICATIONS in", values, "orthodonticTreatmentComplications");
            return (Criteria) this;
        }

        public Criteria andOrthodonticTreatmentComplicationsNotIn(List<String> values) {
            addCriterion("ORTHODONTIC_TREATMENT_COMPLICATIONS not in", values, "orthodonticTreatmentComplications");
            return (Criteria) this;
        }

        public Criteria andOrthodonticTreatmentComplicationsBetween(String value1, String value2) {
            addCriterion("ORTHODONTIC_TREATMENT_COMPLICATIONS between", value1, value2, "orthodonticTreatmentComplications");
            return (Criteria) this;
        }

        public Criteria andOrthodonticTreatmentComplicationsNotBetween(String value1, String value2) {
            addCriterion("ORTHODONTIC_TREATMENT_COMPLICATIONS not between", value1, value2, "orthodonticTreatmentComplications");
            return (Criteria) this;
        }

        public Criteria andRestorativeRxStatusIsNull() {
            addCriterion("RESTORATIVE_RX_STATUS is null");
            return (Criteria) this;
        }

        public Criteria andRestorativeRxStatusIsNotNull() {
            addCriterion("RESTORATIVE_RX_STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andRestorativeRxStatusEqualTo(Byte value) {
            addCriterion("RESTORATIVE_RX_STATUS =", value, "restorativeRxStatus");
            return (Criteria) this;
        }

        public Criteria andRestorativeRxStatusNotEqualTo(Byte value) {
            addCriterion("RESTORATIVE_RX_STATUS <>", value, "restorativeRxStatus");
            return (Criteria) this;
        }

        public Criteria andRestorativeRxStatusGreaterThan(Byte value) {
            addCriterion("RESTORATIVE_RX_STATUS >", value, "restorativeRxStatus");
            return (Criteria) this;
        }

        public Criteria andRestorativeRxStatusGreaterThanOrEqualTo(Byte value) {
            addCriterion("RESTORATIVE_RX_STATUS >=", value, "restorativeRxStatus");
            return (Criteria) this;
        }

        public Criteria andRestorativeRxStatusLessThan(Byte value) {
            addCriterion("RESTORATIVE_RX_STATUS <", value, "restorativeRxStatus");
            return (Criteria) this;
        }

        public Criteria andRestorativeRxStatusLessThanOrEqualTo(Byte value) {
            addCriterion("RESTORATIVE_RX_STATUS <=", value, "restorativeRxStatus");
            return (Criteria) this;
        }

        public Criteria andRestorativeRxStatusIn(List<Byte> values) {
            addCriterion("RESTORATIVE_RX_STATUS in", values, "restorativeRxStatus");
            return (Criteria) this;
        }

        public Criteria andRestorativeRxStatusNotIn(List<Byte> values) {
            addCriterion("RESTORATIVE_RX_STATUS not in", values, "restorativeRxStatus");
            return (Criteria) this;
        }

        public Criteria andRestorativeRxStatusBetween(Byte value1, Byte value2) {
            addCriterion("RESTORATIVE_RX_STATUS between", value1, value2, "restorativeRxStatus");
            return (Criteria) this;
        }

        public Criteria andRestorativeRxStatusNotBetween(Byte value1, Byte value2) {
            addCriterion("RESTORATIVE_RX_STATUS not between", value1, value2, "restorativeRxStatus");
            return (Criteria) this;
        }

        public Criteria andRestorativeRxComplicationsIsNull() {
            addCriterion("RESTORATIVE_RX_COMPLICATIONS is null");
            return (Criteria) this;
        }

        public Criteria andRestorativeRxComplicationsIsNotNull() {
            addCriterion("RESTORATIVE_RX_COMPLICATIONS is not null");
            return (Criteria) this;
        }

        public Criteria andRestorativeRxComplicationsEqualTo(String value) {
            addCriterion("RESTORATIVE_RX_COMPLICATIONS =", value, "restorativeRxComplications");
            return (Criteria) this;
        }

        public Criteria andRestorativeRxComplicationsNotEqualTo(String value) {
            addCriterion("RESTORATIVE_RX_COMPLICATIONS <>", value, "restorativeRxComplications");
            return (Criteria) this;
        }

        public Criteria andRestorativeRxComplicationsGreaterThan(String value) {
            addCriterion("RESTORATIVE_RX_COMPLICATIONS >", value, "restorativeRxComplications");
            return (Criteria) this;
        }

        public Criteria andRestorativeRxComplicationsGreaterThanOrEqualTo(String value) {
            addCriterion("RESTORATIVE_RX_COMPLICATIONS >=", value, "restorativeRxComplications");
            return (Criteria) this;
        }

        public Criteria andRestorativeRxComplicationsLessThan(String value) {
            addCriterion("RESTORATIVE_RX_COMPLICATIONS <", value, "restorativeRxComplications");
            return (Criteria) this;
        }

        public Criteria andRestorativeRxComplicationsLessThanOrEqualTo(String value) {
            addCriterion("RESTORATIVE_RX_COMPLICATIONS <=", value, "restorativeRxComplications");
            return (Criteria) this;
        }

        public Criteria andRestorativeRxComplicationsLike(String value) {
            addCriterion("RESTORATIVE_RX_COMPLICATIONS like", value, "restorativeRxComplications");
            return (Criteria) this;
        }

        public Criteria andRestorativeRxComplicationsNotLike(String value) {
            addCriterion("RESTORATIVE_RX_COMPLICATIONS not like", value, "restorativeRxComplications");
            return (Criteria) this;
        }

        public Criteria andRestorativeRxComplicationsIn(List<String> values) {
            addCriterion("RESTORATIVE_RX_COMPLICATIONS in", values, "restorativeRxComplications");
            return (Criteria) this;
        }

        public Criteria andRestorativeRxComplicationsNotIn(List<String> values) {
            addCriterion("RESTORATIVE_RX_COMPLICATIONS not in", values, "restorativeRxComplications");
            return (Criteria) this;
        }

        public Criteria andRestorativeRxComplicationsBetween(String value1, String value2) {
            addCriterion("RESTORATIVE_RX_COMPLICATIONS between", value1, value2, "restorativeRxComplications");
            return (Criteria) this;
        }

        public Criteria andRestorativeRxComplicationsNotBetween(String value1, String value2) {
            addCriterion("RESTORATIVE_RX_COMPLICATIONS not between", value1, value2, "restorativeRxComplications");
            return (Criteria) this;
        }

        public Criteria andProsthesisRxStatusIsNull() {
            addCriterion("PROSTHESIS_RX_STATUS is null");
            return (Criteria) this;
        }

        public Criteria andProsthesisRxStatusIsNotNull() {
            addCriterion("PROSTHESIS_RX_STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andProsthesisRxStatusEqualTo(Byte value) {
            addCriterion("PROSTHESIS_RX_STATUS =", value, "prosthesisRxStatus");
            return (Criteria) this;
        }

        public Criteria andProsthesisRxStatusNotEqualTo(Byte value) {
            addCriterion("PROSTHESIS_RX_STATUS <>", value, "prosthesisRxStatus");
            return (Criteria) this;
        }

        public Criteria andProsthesisRxStatusGreaterThan(Byte value) {
            addCriterion("PROSTHESIS_RX_STATUS >", value, "prosthesisRxStatus");
            return (Criteria) this;
        }

        public Criteria andProsthesisRxStatusGreaterThanOrEqualTo(Byte value) {
            addCriterion("PROSTHESIS_RX_STATUS >=", value, "prosthesisRxStatus");
            return (Criteria) this;
        }

        public Criteria andProsthesisRxStatusLessThan(Byte value) {
            addCriterion("PROSTHESIS_RX_STATUS <", value, "prosthesisRxStatus");
            return (Criteria) this;
        }

        public Criteria andProsthesisRxStatusLessThanOrEqualTo(Byte value) {
            addCriterion("PROSTHESIS_RX_STATUS <=", value, "prosthesisRxStatus");
            return (Criteria) this;
        }

        public Criteria andProsthesisRxStatusIn(List<Byte> values) {
            addCriterion("PROSTHESIS_RX_STATUS in", values, "prosthesisRxStatus");
            return (Criteria) this;
        }

        public Criteria andProsthesisRxStatusNotIn(List<Byte> values) {
            addCriterion("PROSTHESIS_RX_STATUS not in", values, "prosthesisRxStatus");
            return (Criteria) this;
        }

        public Criteria andProsthesisRxStatusBetween(Byte value1, Byte value2) {
            addCriterion("PROSTHESIS_RX_STATUS between", value1, value2, "prosthesisRxStatus");
            return (Criteria) this;
        }

        public Criteria andProsthesisRxStatusNotBetween(Byte value1, Byte value2) {
            addCriterion("PROSTHESIS_RX_STATUS not between", value1, value2, "prosthesisRxStatus");
            return (Criteria) this;
        }

        public Criteria andProsthesisRxComplicationsIsNull() {
            addCriterion("PROSTHESIS_RX_COMPLICATIONS is null");
            return (Criteria) this;
        }

        public Criteria andProsthesisRxComplicationsIsNotNull() {
            addCriterion("PROSTHESIS_RX_COMPLICATIONS is not null");
            return (Criteria) this;
        }

        public Criteria andProsthesisRxComplicationsEqualTo(String value) {
            addCriterion("PROSTHESIS_RX_COMPLICATIONS =", value, "prosthesisRxComplications");
            return (Criteria) this;
        }

        public Criteria andProsthesisRxComplicationsNotEqualTo(String value) {
            addCriterion("PROSTHESIS_RX_COMPLICATIONS <>", value, "prosthesisRxComplications");
            return (Criteria) this;
        }

        public Criteria andProsthesisRxComplicationsGreaterThan(String value) {
            addCriterion("PROSTHESIS_RX_COMPLICATIONS >", value, "prosthesisRxComplications");
            return (Criteria) this;
        }

        public Criteria andProsthesisRxComplicationsGreaterThanOrEqualTo(String value) {
            addCriterion("PROSTHESIS_RX_COMPLICATIONS >=", value, "prosthesisRxComplications");
            return (Criteria) this;
        }

        public Criteria andProsthesisRxComplicationsLessThan(String value) {
            addCriterion("PROSTHESIS_RX_COMPLICATIONS <", value, "prosthesisRxComplications");
            return (Criteria) this;
        }

        public Criteria andProsthesisRxComplicationsLessThanOrEqualTo(String value) {
            addCriterion("PROSTHESIS_RX_COMPLICATIONS <=", value, "prosthesisRxComplications");
            return (Criteria) this;
        }

        public Criteria andProsthesisRxComplicationsLike(String value) {
            addCriterion("PROSTHESIS_RX_COMPLICATIONS like", value, "prosthesisRxComplications");
            return (Criteria) this;
        }

        public Criteria andProsthesisRxComplicationsNotLike(String value) {
            addCriterion("PROSTHESIS_RX_COMPLICATIONS not like", value, "prosthesisRxComplications");
            return (Criteria) this;
        }

        public Criteria andProsthesisRxComplicationsIn(List<String> values) {
            addCriterion("PROSTHESIS_RX_COMPLICATIONS in", values, "prosthesisRxComplications");
            return (Criteria) this;
        }

        public Criteria andProsthesisRxComplicationsNotIn(List<String> values) {
            addCriterion("PROSTHESIS_RX_COMPLICATIONS not in", values, "prosthesisRxComplications");
            return (Criteria) this;
        }

        public Criteria andProsthesisRxComplicationsBetween(String value1, String value2) {
            addCriterion("PROSTHESIS_RX_COMPLICATIONS between", value1, value2, "prosthesisRxComplications");
            return (Criteria) this;
        }

        public Criteria andProsthesisRxComplicationsNotBetween(String value1, String value2) {
            addCriterion("PROSTHESIS_RX_COMPLICATIONS not between", value1, value2, "prosthesisRxComplications");
            return (Criteria) this;
        }

        public Criteria andCommentIsNull() {
            addCriterion("COMMENT is null");
            return (Criteria) this;
        }

        public Criteria andCommentIsNotNull() {
            addCriterion("COMMENT is not null");
            return (Criteria) this;
        }

        public Criteria andCommentEqualTo(String value) {
            addCriterion("COMMENT =", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentNotEqualTo(String value) {
            addCriterion("COMMENT <>", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentGreaterThan(String value) {
            addCriterion("COMMENT >", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentGreaterThanOrEqualTo(String value) {
            addCriterion("COMMENT >=", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentLessThan(String value) {
            addCriterion("COMMENT <", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentLessThanOrEqualTo(String value) {
            addCriterion("COMMENT <=", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentLike(String value) {
            addCriterion("COMMENT like", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentNotLike(String value) {
            addCriterion("COMMENT not like", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentIn(List<String> values) {
            addCriterion("COMMENT in", values, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentNotIn(List<String> values) {
            addCriterion("COMMENT not in", values, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentBetween(String value1, String value2) {
            addCriterion("COMMENT between", value1, value2, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentNotBetween(String value1, String value2) {
            addCriterion("COMMENT not between", value1, value2, "comment");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("STATUS is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Byte value) {
            addCriterion("STATUS =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Byte value) {
            addCriterion("STATUS <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Byte value) {
            addCriterion("STATUS >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Byte value) {
            addCriterion("STATUS >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Byte value) {
            addCriterion("STATUS <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Byte value) {
            addCriterion("STATUS <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Byte> values) {
            addCriterion("STATUS in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Byte> values) {
            addCriterion("STATUS not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Byte value1, Byte value2) {
            addCriterion("STATUS between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Byte value1, Byte value2) {
            addCriterion("STATUS not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andSortOrderIsNull() {
            addCriterion("SORT_ORDER is null");
            return (Criteria) this;
        }

        public Criteria andSortOrderIsNotNull() {
            addCriterion("SORT_ORDER is not null");
            return (Criteria) this;
        }

        public Criteria andSortOrderEqualTo(Integer value) {
            addCriterion("SORT_ORDER =", value, "sortOrder");
            return (Criteria) this;
        }

        public Criteria andSortOrderNotEqualTo(Integer value) {
            addCriterion("SORT_ORDER <>", value, "sortOrder");
            return (Criteria) this;
        }

        public Criteria andSortOrderGreaterThan(Integer value) {
            addCriterion("SORT_ORDER >", value, "sortOrder");
            return (Criteria) this;
        }

        public Criteria andSortOrderGreaterThanOrEqualTo(Integer value) {
            addCriterion("SORT_ORDER >=", value, "sortOrder");
            return (Criteria) this;
        }

        public Criteria andSortOrderLessThan(Integer value) {
            addCriterion("SORT_ORDER <", value, "sortOrder");
            return (Criteria) this;
        }

        public Criteria andSortOrderLessThanOrEqualTo(Integer value) {
            addCriterion("SORT_ORDER <=", value, "sortOrder");
            return (Criteria) this;
        }

        public Criteria andSortOrderIn(List<Integer> values) {
            addCriterion("SORT_ORDER in", values, "sortOrder");
            return (Criteria) this;
        }

        public Criteria andSortOrderNotIn(List<Integer> values) {
            addCriterion("SORT_ORDER not in", values, "sortOrder");
            return (Criteria) this;
        }

        public Criteria andSortOrderBetween(Integer value1, Integer value2) {
            addCriterion("SORT_ORDER between", value1, value2, "sortOrder");
            return (Criteria) this;
        }

        public Criteria andSortOrderNotBetween(Integer value1, Integer value2) {
            addCriterion("SORT_ORDER not between", value1, value2, "sortOrder");
            return (Criteria) this;
        }

        public Criteria andInsertUserIdIsNull() {
            addCriterion("INSERT_USER_ID is null");
            return (Criteria) this;
        }

        public Criteria andInsertUserIdIsNotNull() {
            addCriterion("INSERT_USER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andInsertUserIdEqualTo(String value) {
            addCriterion("INSERT_USER_ID =", value, "insertUserId");
            return (Criteria) this;
        }

        public Criteria andInsertUserIdNotEqualTo(String value) {
            addCriterion("INSERT_USER_ID <>", value, "insertUserId");
            return (Criteria) this;
        }

        public Criteria andInsertUserIdGreaterThan(String value) {
            addCriterion("INSERT_USER_ID >", value, "insertUserId");
            return (Criteria) this;
        }

        public Criteria andInsertUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("INSERT_USER_ID >=", value, "insertUserId");
            return (Criteria) this;
        }

        public Criteria andInsertUserIdLessThan(String value) {
            addCriterion("INSERT_USER_ID <", value, "insertUserId");
            return (Criteria) this;
        }

        public Criteria andInsertUserIdLessThanOrEqualTo(String value) {
            addCriterion("INSERT_USER_ID <=", value, "insertUserId");
            return (Criteria) this;
        }

        public Criteria andInsertUserIdLike(String value) {
            addCriterion("INSERT_USER_ID like", value, "insertUserId");
            return (Criteria) this;
        }

        public Criteria andInsertUserIdNotLike(String value) {
            addCriterion("INSERT_USER_ID not like", value, "insertUserId");
            return (Criteria) this;
        }

        public Criteria andInsertUserIdIn(List<String> values) {
            addCriterion("INSERT_USER_ID in", values, "insertUserId");
            return (Criteria) this;
        }

        public Criteria andInsertUserIdNotIn(List<String> values) {
            addCriterion("INSERT_USER_ID not in", values, "insertUserId");
            return (Criteria) this;
        }

        public Criteria andInsertUserIdBetween(String value1, String value2) {
            addCriterion("INSERT_USER_ID between", value1, value2, "insertUserId");
            return (Criteria) this;
        }

        public Criteria andInsertUserIdNotBetween(String value1, String value2) {
            addCriterion("INSERT_USER_ID not between", value1, value2, "insertUserId");
            return (Criteria) this;
        }

        public Criteria andInsertDatetimeIsNull() {
            addCriterion("INSERT_DATETIME is null");
            return (Criteria) this;
        }

        public Criteria andInsertDatetimeIsNotNull() {
            addCriterion("INSERT_DATETIME is not null");
            return (Criteria) this;
        }

        public Criteria andInsertDatetimeEqualTo(Date value) {
            addCriterion("INSERT_DATETIME =", value, "insertDatetime");
            return (Criteria) this;
        }

        public Criteria andInsertDatetimeNotEqualTo(Date value) {
            addCriterion("INSERT_DATETIME <>", value, "insertDatetime");
            return (Criteria) this;
        }

        public Criteria andInsertDatetimeGreaterThan(Date value) {
            addCriterion("INSERT_DATETIME >", value, "insertDatetime");
            return (Criteria) this;
        }

        public Criteria andInsertDatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("INSERT_DATETIME >=", value, "insertDatetime");
            return (Criteria) this;
        }

        public Criteria andInsertDatetimeLessThan(Date value) {
            addCriterion("INSERT_DATETIME <", value, "insertDatetime");
            return (Criteria) this;
        }

        public Criteria andInsertDatetimeLessThanOrEqualTo(Date value) {
            addCriterion("INSERT_DATETIME <=", value, "insertDatetime");
            return (Criteria) this;
        }

        public Criteria andInsertDatetimeIn(List<Date> values) {
            addCriterion("INSERT_DATETIME in", values, "insertDatetime");
            return (Criteria) this;
        }

        public Criteria andInsertDatetimeNotIn(List<Date> values) {
            addCriterion("INSERT_DATETIME not in", values, "insertDatetime");
            return (Criteria) this;
        }

        public Criteria andInsertDatetimeBetween(Date value1, Date value2) {
            addCriterion("INSERT_DATETIME between", value1, value2, "insertDatetime");
            return (Criteria) this;
        }

        public Criteria andInsertDatetimeNotBetween(Date value1, Date value2) {
            addCriterion("INSERT_DATETIME not between", value1, value2, "insertDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdIsNull() {
            addCriterion("UPDATE_USER_ID is null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdIsNotNull() {
            addCriterion("UPDATE_USER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdEqualTo(String value) {
            addCriterion("UPDATE_USER_ID =", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotEqualTo(String value) {
            addCriterion("UPDATE_USER_ID <>", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdGreaterThan(String value) {
            addCriterion("UPDATE_USER_ID >", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("UPDATE_USER_ID >=", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdLessThan(String value) {
            addCriterion("UPDATE_USER_ID <", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdLessThanOrEqualTo(String value) {
            addCriterion("UPDATE_USER_ID <=", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdLike(String value) {
            addCriterion("UPDATE_USER_ID like", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotLike(String value) {
            addCriterion("UPDATE_USER_ID not like", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdIn(List<String> values) {
            addCriterion("UPDATE_USER_ID in", values, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotIn(List<String> values) {
            addCriterion("UPDATE_USER_ID not in", values, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdBetween(String value1, String value2) {
            addCriterion("UPDATE_USER_ID between", value1, value2, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotBetween(String value1, String value2) {
            addCriterion("UPDATE_USER_ID not between", value1, value2, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeIsNull() {
            addCriterion("UPDATE_DATETIME is null");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeIsNotNull() {
            addCriterion("UPDATE_DATETIME is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeEqualTo(Date value) {
            addCriterion("UPDATE_DATETIME =", value, "updateDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeNotEqualTo(Date value) {
            addCriterion("UPDATE_DATETIME <>", value, "updateDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeGreaterThan(Date value) {
            addCriterion("UPDATE_DATETIME >", value, "updateDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("UPDATE_DATETIME >=", value, "updateDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeLessThan(Date value) {
            addCriterion("UPDATE_DATETIME <", value, "updateDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeLessThanOrEqualTo(Date value) {
            addCriterion("UPDATE_DATETIME <=", value, "updateDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeIn(List<Date> values) {
            addCriterion("UPDATE_DATETIME in", values, "updateDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeNotIn(List<Date> values) {
            addCriterion("UPDATE_DATETIME not in", values, "updateDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeBetween(Date value1, Date value2) {
            addCriterion("UPDATE_DATETIME between", value1, value2, "updateDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeNotBetween(Date value1, Date value2) {
            addCriterion("UPDATE_DATETIME not between", value1, value2, "updateDatetime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tbl_patient_past_dental_history
     *
     * @mbg.generated do_not_delete_during_merge Tue Dec 19 03:23:32 IST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tbl_patient_past_dental_history
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }
    }
}