package com.doerit.model.diagnostic;

import java.util.Date;

public class PatientHabit {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_patient_habit.ID
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_patient_habit.PATIENT_ID
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    private String patientId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_patient_habit.HABIT_ID
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    private String habitId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_patient_habit.FREQUENCY
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    private String frequency;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_patient_habit.DURATION
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    private String duration;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_patient_habit.DATA_ADDED_BY
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    private String dataAddedBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_patient_habit.APPROVED_BY
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    private String approvedBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_patient_habit.COMMENT
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    private String comment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_patient_habit.STATUS
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_patient_habit.SORT_ORDER
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    private Integer sortOrder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_patient_habit.INSERT_USER_ID
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    private String insertUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_patient_habit.INSERT_DATETIME
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    private Date insertDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_patient_habit.UPDATE_USER_ID
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    private String updateUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_patient_habit.UPDATE_DATETIME
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    private Date updateDatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_patient_habit.ID
     *
     * @return the value of tbl_patient_habit.ID
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_patient_habit.ID
     *
     * @param id the value for tbl_patient_habit.ID
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_patient_habit.PATIENT_ID
     *
     * @return the value of tbl_patient_habit.PATIENT_ID
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public String getPatientId() {
        return patientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_patient_habit.PATIENT_ID
     *
     * @param patientId the value for tbl_patient_habit.PATIENT_ID
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public void setPatientId(String patientId) {
        this.patientId = patientId == null ? null : patientId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_patient_habit.HABIT_ID
     *
     * @return the value of tbl_patient_habit.HABIT_ID
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public String getHabitId() {
        return habitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_patient_habit.HABIT_ID
     *
     * @param habitId the value for tbl_patient_habit.HABIT_ID
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public void setHabitId(String habitId) {
        this.habitId = habitId == null ? null : habitId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_patient_habit.FREQUENCY
     *
     * @return the value of tbl_patient_habit.FREQUENCY
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public String getFrequency() {
        return frequency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_patient_habit.FREQUENCY
     *
     * @param frequency the value for tbl_patient_habit.FREQUENCY
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public void setFrequency(String frequency) {
        this.frequency = frequency == null ? null : frequency.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_patient_habit.DURATION
     *
     * @return the value of tbl_patient_habit.DURATION
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public String getDuration() {
        return duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_patient_habit.DURATION
     *
     * @param duration the value for tbl_patient_habit.DURATION
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public void setDuration(String duration) {
        this.duration = duration == null ? null : duration.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_patient_habit.DATA_ADDED_BY
     *
     * @return the value of tbl_patient_habit.DATA_ADDED_BY
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public String getDataAddedBy() {
        return dataAddedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_patient_habit.DATA_ADDED_BY
     *
     * @param dataAddedBy the value for tbl_patient_habit.DATA_ADDED_BY
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public void setDataAddedBy(String dataAddedBy) {
        this.dataAddedBy = dataAddedBy == null ? null : dataAddedBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_patient_habit.APPROVED_BY
     *
     * @return the value of tbl_patient_habit.APPROVED_BY
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public String getApprovedBy() {
        return approvedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_patient_habit.APPROVED_BY
     *
     * @param approvedBy the value for tbl_patient_habit.APPROVED_BY
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public void setApprovedBy(String approvedBy) {
        this.approvedBy = approvedBy == null ? null : approvedBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_patient_habit.COMMENT
     *
     * @return the value of tbl_patient_habit.COMMENT
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_patient_habit.COMMENT
     *
     * @param comment the value for tbl_patient_habit.COMMENT
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_patient_habit.STATUS
     *
     * @return the value of tbl_patient_habit.STATUS
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_patient_habit.STATUS
     *
     * @param status the value for tbl_patient_habit.STATUS
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_patient_habit.SORT_ORDER
     *
     * @return the value of tbl_patient_habit.SORT_ORDER
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public Integer getSortOrder() {
        return sortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_patient_habit.SORT_ORDER
     *
     * @param sortOrder the value for tbl_patient_habit.SORT_ORDER
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public void setSortOrder(Integer sortOrder) {
        this.sortOrder = sortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_patient_habit.INSERT_USER_ID
     *
     * @return the value of tbl_patient_habit.INSERT_USER_ID
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public String getInsertUserId() {
        return insertUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_patient_habit.INSERT_USER_ID
     *
     * @param insertUserId the value for tbl_patient_habit.INSERT_USER_ID
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public void setInsertUserId(String insertUserId) {
        this.insertUserId = insertUserId == null ? null : insertUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_patient_habit.INSERT_DATETIME
     *
     * @return the value of tbl_patient_habit.INSERT_DATETIME
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public Date getInsertDatetime() {
        return insertDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_patient_habit.INSERT_DATETIME
     *
     * @param insertDatetime the value for tbl_patient_habit.INSERT_DATETIME
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public void setInsertDatetime(Date insertDatetime) {
        this.insertDatetime = insertDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_patient_habit.UPDATE_USER_ID
     *
     * @return the value of tbl_patient_habit.UPDATE_USER_ID
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public String getUpdateUserId() {
        return updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_patient_habit.UPDATE_USER_ID
     *
     * @param updateUserId the value for tbl_patient_habit.UPDATE_USER_ID
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public void setUpdateUserId(String updateUserId) {
        this.updateUserId = updateUserId == null ? null : updateUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_patient_habit.UPDATE_DATETIME
     *
     * @return the value of tbl_patient_habit.UPDATE_DATETIME
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public Date getUpdateDatetime() {
        return updateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_patient_habit.UPDATE_DATETIME
     *
     * @param updateDatetime the value for tbl_patient_habit.UPDATE_DATETIME
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public void setUpdateDatetime(Date updateDatetime) {
        this.updateDatetime = updateDatetime;
    }
}