package com.doerit.model.diagnostic;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class PlaqueControlExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tbl_patient_plaque_control
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tbl_patient_plaque_control
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tbl_patient_plaque_control
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_patient_plaque_control
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public PlaqueControlExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_patient_plaque_control
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_patient_plaque_control
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_patient_plaque_control
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_patient_plaque_control
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_patient_plaque_control
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_patient_plaque_control
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_patient_plaque_control
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_patient_plaque_control
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_patient_plaque_control
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_patient_plaque_control
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tbl_patient_plaque_control
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("ID like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("ID not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andItemIsNull() {
            addCriterion("ITEM is null");
            return (Criteria) this;
        }

        public Criteria andItemIsNotNull() {
            addCriterion("ITEM is not null");
            return (Criteria) this;
        }

        public Criteria andItemEqualTo(String value) {
            addCriterion("ITEM =", value, "item");
            return (Criteria) this;
        }

        public Criteria andItemNotEqualTo(String value) {
            addCriterion("ITEM <>", value, "item");
            return (Criteria) this;
        }

        public Criteria andItemGreaterThan(String value) {
            addCriterion("ITEM >", value, "item");
            return (Criteria) this;
        }

        public Criteria andItemGreaterThanOrEqualTo(String value) {
            addCriterion("ITEM >=", value, "item");
            return (Criteria) this;
        }

        public Criteria andItemLessThan(String value) {
            addCriterion("ITEM <", value, "item");
            return (Criteria) this;
        }

        public Criteria andItemLessThanOrEqualTo(String value) {
            addCriterion("ITEM <=", value, "item");
            return (Criteria) this;
        }

        public Criteria andItemLike(String value) {
            addCriterion("ITEM like", value, "item");
            return (Criteria) this;
        }

        public Criteria andItemNotLike(String value) {
            addCriterion("ITEM not like", value, "item");
            return (Criteria) this;
        }

        public Criteria andItemIn(List<String> values) {
            addCriterion("ITEM in", values, "item");
            return (Criteria) this;
        }

        public Criteria andItemNotIn(List<String> values) {
            addCriterion("ITEM not in", values, "item");
            return (Criteria) this;
        }

        public Criteria andItemBetween(String value1, String value2) {
            addCriterion("ITEM between", value1, value2, "item");
            return (Criteria) this;
        }

        public Criteria andItemNotBetween(String value1, String value2) {
            addCriterion("ITEM not between", value1, value2, "item");
            return (Criteria) this;
        }

        public Criteria andOptionIsNull() {
            addCriterion("OPTION is null");
            return (Criteria) this;
        }

        public Criteria andOptionIsNotNull() {
            addCriterion("OPTION is not null");
            return (Criteria) this;
        }

        public Criteria andOptionEqualTo(String value) {
            addCriterion("OPTION =", value, "option");
            return (Criteria) this;
        }

        public Criteria andOptionNotEqualTo(String value) {
            addCriterion("OPTION <>", value, "option");
            return (Criteria) this;
        }

        public Criteria andOptionGreaterThan(String value) {
            addCriterion("OPTION >", value, "option");
            return (Criteria) this;
        }

        public Criteria andOptionGreaterThanOrEqualTo(String value) {
            addCriterion("OPTION >=", value, "option");
            return (Criteria) this;
        }

        public Criteria andOptionLessThan(String value) {
            addCriterion("OPTION <", value, "option");
            return (Criteria) this;
        }

        public Criteria andOptionLessThanOrEqualTo(String value) {
            addCriterion("OPTION <=", value, "option");
            return (Criteria) this;
        }

        public Criteria andOptionLike(String value) {
            addCriterion("OPTION like", value, "option");
            return (Criteria) this;
        }

        public Criteria andOptionNotLike(String value) {
            addCriterion("OPTION not like", value, "option");
            return (Criteria) this;
        }

        public Criteria andOptionIn(List<String> values) {
            addCriterion("OPTION in", values, "option");
            return (Criteria) this;
        }

        public Criteria andOptionNotIn(List<String> values) {
            addCriterion("OPTION not in", values, "option");
            return (Criteria) this;
        }

        public Criteria andOptionBetween(String value1, String value2) {
            addCriterion("OPTION between", value1, value2, "option");
            return (Criteria) this;
        }

        public Criteria andOptionNotBetween(String value1, String value2) {
            addCriterion("OPTION not between", value1, value2, "option");
            return (Criteria) this;
        }

        public Criteria andBrushingToolIsNull() {
            addCriterion("BRUSHING_TOOL is null");
            return (Criteria) this;
        }

        public Criteria andBrushingToolIsNotNull() {
            addCriterion("BRUSHING_TOOL is not null");
            return (Criteria) this;
        }

        public Criteria andBrushingToolEqualTo(String value) {
            addCriterion("BRUSHING_TOOL =", value, "brushingTool");
            return (Criteria) this;
        }

        public Criteria andBrushingToolNotEqualTo(String value) {
            addCriterion("BRUSHING_TOOL <>", value, "brushingTool");
            return (Criteria) this;
        }

        public Criteria andBrushingToolGreaterThan(String value) {
            addCriterion("BRUSHING_TOOL >", value, "brushingTool");
            return (Criteria) this;
        }

        public Criteria andBrushingToolGreaterThanOrEqualTo(String value) {
            addCriterion("BRUSHING_TOOL >=", value, "brushingTool");
            return (Criteria) this;
        }

        public Criteria andBrushingToolLessThan(String value) {
            addCriterion("BRUSHING_TOOL <", value, "brushingTool");
            return (Criteria) this;
        }

        public Criteria andBrushingToolLessThanOrEqualTo(String value) {
            addCriterion("BRUSHING_TOOL <=", value, "brushingTool");
            return (Criteria) this;
        }

        public Criteria andBrushingToolLike(String value) {
            addCriterion("BRUSHING_TOOL like", value, "brushingTool");
            return (Criteria) this;
        }

        public Criteria andBrushingToolNotLike(String value) {
            addCriterion("BRUSHING_TOOL not like", value, "brushingTool");
            return (Criteria) this;
        }

        public Criteria andBrushingToolIn(List<String> values) {
            addCriterion("BRUSHING_TOOL in", values, "brushingTool");
            return (Criteria) this;
        }

        public Criteria andBrushingToolNotIn(List<String> values) {
            addCriterion("BRUSHING_TOOL not in", values, "brushingTool");
            return (Criteria) this;
        }

        public Criteria andBrushingToolBetween(String value1, String value2) {
            addCriterion("BRUSHING_TOOL between", value1, value2, "brushingTool");
            return (Criteria) this;
        }

        public Criteria andBrushingToolNotBetween(String value1, String value2) {
            addCriterion("BRUSHING_TOOL not between", value1, value2, "brushingTool");
            return (Criteria) this;
        }

        public Criteria andBrushingFrequencyIsNull() {
            addCriterion("BRUSHING_FREQUENCY is null");
            return (Criteria) this;
        }

        public Criteria andBrushingFrequencyIsNotNull() {
            addCriterion("BRUSHING_FREQUENCY is not null");
            return (Criteria) this;
        }

        public Criteria andBrushingFrequencyEqualTo(String value) {
            addCriterion("BRUSHING_FREQUENCY =", value, "brushingFrequency");
            return (Criteria) this;
        }

        public Criteria andBrushingFrequencyNotEqualTo(String value) {
            addCriterion("BRUSHING_FREQUENCY <>", value, "brushingFrequency");
            return (Criteria) this;
        }

        public Criteria andBrushingFrequencyGreaterThan(String value) {
            addCriterion("BRUSHING_FREQUENCY >", value, "brushingFrequency");
            return (Criteria) this;
        }

        public Criteria andBrushingFrequencyGreaterThanOrEqualTo(String value) {
            addCriterion("BRUSHING_FREQUENCY >=", value, "brushingFrequency");
            return (Criteria) this;
        }

        public Criteria andBrushingFrequencyLessThan(String value) {
            addCriterion("BRUSHING_FREQUENCY <", value, "brushingFrequency");
            return (Criteria) this;
        }

        public Criteria andBrushingFrequencyLessThanOrEqualTo(String value) {
            addCriterion("BRUSHING_FREQUENCY <=", value, "brushingFrequency");
            return (Criteria) this;
        }

        public Criteria andBrushingFrequencyLike(String value) {
            addCriterion("BRUSHING_FREQUENCY like", value, "brushingFrequency");
            return (Criteria) this;
        }

        public Criteria andBrushingFrequencyNotLike(String value) {
            addCriterion("BRUSHING_FREQUENCY not like", value, "brushingFrequency");
            return (Criteria) this;
        }

        public Criteria andBrushingFrequencyIn(List<String> values) {
            addCriterion("BRUSHING_FREQUENCY in", values, "brushingFrequency");
            return (Criteria) this;
        }

        public Criteria andBrushingFrequencyNotIn(List<String> values) {
            addCriterion("BRUSHING_FREQUENCY not in", values, "brushingFrequency");
            return (Criteria) this;
        }

        public Criteria andBrushingFrequencyBetween(String value1, String value2) {
            addCriterion("BRUSHING_FREQUENCY between", value1, value2, "brushingFrequency");
            return (Criteria) this;
        }

        public Criteria andBrushingFrequencyNotBetween(String value1, String value2) {
            addCriterion("BRUSHING_FREQUENCY not between", value1, value2, "brushingFrequency");
            return (Criteria) this;
        }

        public Criteria andBristlesIsNull() {
            addCriterion("BRISTLES is null");
            return (Criteria) this;
        }

        public Criteria andBristlesIsNotNull() {
            addCriterion("BRISTLES is not null");
            return (Criteria) this;
        }

        public Criteria andBristlesEqualTo(String value) {
            addCriterion("BRISTLES =", value, "bristles");
            return (Criteria) this;
        }

        public Criteria andBristlesNotEqualTo(String value) {
            addCriterion("BRISTLES <>", value, "bristles");
            return (Criteria) this;
        }

        public Criteria andBristlesGreaterThan(String value) {
            addCriterion("BRISTLES >", value, "bristles");
            return (Criteria) this;
        }

        public Criteria andBristlesGreaterThanOrEqualTo(String value) {
            addCriterion("BRISTLES >=", value, "bristles");
            return (Criteria) this;
        }

        public Criteria andBristlesLessThan(String value) {
            addCriterion("BRISTLES <", value, "bristles");
            return (Criteria) this;
        }

        public Criteria andBristlesLessThanOrEqualTo(String value) {
            addCriterion("BRISTLES <=", value, "bristles");
            return (Criteria) this;
        }

        public Criteria andBristlesLike(String value) {
            addCriterion("BRISTLES like", value, "bristles");
            return (Criteria) this;
        }

        public Criteria andBristlesNotLike(String value) {
            addCriterion("BRISTLES not like", value, "bristles");
            return (Criteria) this;
        }

        public Criteria andBristlesIn(List<String> values) {
            addCriterion("BRISTLES in", values, "bristles");
            return (Criteria) this;
        }

        public Criteria andBristlesNotIn(List<String> values) {
            addCriterion("BRISTLES not in", values, "bristles");
            return (Criteria) this;
        }

        public Criteria andBristlesBetween(String value1, String value2) {
            addCriterion("BRISTLES between", value1, value2, "bristles");
            return (Criteria) this;
        }

        public Criteria andBristlesNotBetween(String value1, String value2) {
            addCriterion("BRISTLES not between", value1, value2, "bristles");
            return (Criteria) this;
        }

        public Criteria andBrushingDurationIsNull() {
            addCriterion("BRUSHING_DURATION is null");
            return (Criteria) this;
        }

        public Criteria andBrushingDurationIsNotNull() {
            addCriterion("BRUSHING_DURATION is not null");
            return (Criteria) this;
        }

        public Criteria andBrushingDurationEqualTo(String value) {
            addCriterion("BRUSHING_DURATION =", value, "brushingDuration");
            return (Criteria) this;
        }

        public Criteria andBrushingDurationNotEqualTo(String value) {
            addCriterion("BRUSHING_DURATION <>", value, "brushingDuration");
            return (Criteria) this;
        }

        public Criteria andBrushingDurationGreaterThan(String value) {
            addCriterion("BRUSHING_DURATION >", value, "brushingDuration");
            return (Criteria) this;
        }

        public Criteria andBrushingDurationGreaterThanOrEqualTo(String value) {
            addCriterion("BRUSHING_DURATION >=", value, "brushingDuration");
            return (Criteria) this;
        }

        public Criteria andBrushingDurationLessThan(String value) {
            addCriterion("BRUSHING_DURATION <", value, "brushingDuration");
            return (Criteria) this;
        }

        public Criteria andBrushingDurationLessThanOrEqualTo(String value) {
            addCriterion("BRUSHING_DURATION <=", value, "brushingDuration");
            return (Criteria) this;
        }

        public Criteria andBrushingDurationLike(String value) {
            addCriterion("BRUSHING_DURATION like", value, "brushingDuration");
            return (Criteria) this;
        }

        public Criteria andBrushingDurationNotLike(String value) {
            addCriterion("BRUSHING_DURATION not like", value, "brushingDuration");
            return (Criteria) this;
        }

        public Criteria andBrushingDurationIn(List<String> values) {
            addCriterion("BRUSHING_DURATION in", values, "brushingDuration");
            return (Criteria) this;
        }

        public Criteria andBrushingDurationNotIn(List<String> values) {
            addCriterion("BRUSHING_DURATION not in", values, "brushingDuration");
            return (Criteria) this;
        }

        public Criteria andBrushingDurationBetween(String value1, String value2) {
            addCriterion("BRUSHING_DURATION between", value1, value2, "brushingDuration");
            return (Criteria) this;
        }

        public Criteria andBrushingDurationNotBetween(String value1, String value2) {
            addCriterion("BRUSHING_DURATION not between", value1, value2, "brushingDuration");
            return (Criteria) this;
        }

        public Criteria andToothPasteTypeIsNull() {
            addCriterion("TOOTH_PASTE_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andToothPasteTypeIsNotNull() {
            addCriterion("TOOTH_PASTE_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andToothPasteTypeEqualTo(String value) {
            addCriterion("TOOTH_PASTE_TYPE =", value, "toothPasteType");
            return (Criteria) this;
        }

        public Criteria andToothPasteTypeNotEqualTo(String value) {
            addCriterion("TOOTH_PASTE_TYPE <>", value, "toothPasteType");
            return (Criteria) this;
        }

        public Criteria andToothPasteTypeGreaterThan(String value) {
            addCriterion("TOOTH_PASTE_TYPE >", value, "toothPasteType");
            return (Criteria) this;
        }

        public Criteria andToothPasteTypeGreaterThanOrEqualTo(String value) {
            addCriterion("TOOTH_PASTE_TYPE >=", value, "toothPasteType");
            return (Criteria) this;
        }

        public Criteria andToothPasteTypeLessThan(String value) {
            addCriterion("TOOTH_PASTE_TYPE <", value, "toothPasteType");
            return (Criteria) this;
        }

        public Criteria andToothPasteTypeLessThanOrEqualTo(String value) {
            addCriterion("TOOTH_PASTE_TYPE <=", value, "toothPasteType");
            return (Criteria) this;
        }

        public Criteria andToothPasteTypeLike(String value) {
            addCriterion("TOOTH_PASTE_TYPE like", value, "toothPasteType");
            return (Criteria) this;
        }

        public Criteria andToothPasteTypeNotLike(String value) {
            addCriterion("TOOTH_PASTE_TYPE not like", value, "toothPasteType");
            return (Criteria) this;
        }

        public Criteria andToothPasteTypeIn(List<String> values) {
            addCriterion("TOOTH_PASTE_TYPE in", values, "toothPasteType");
            return (Criteria) this;
        }

        public Criteria andToothPasteTypeNotIn(List<String> values) {
            addCriterion("TOOTH_PASTE_TYPE not in", values, "toothPasteType");
            return (Criteria) this;
        }

        public Criteria andToothPasteTypeBetween(String value1, String value2) {
            addCriterion("TOOTH_PASTE_TYPE between", value1, value2, "toothPasteType");
            return (Criteria) this;
        }

        public Criteria andToothPasteTypeNotBetween(String value1, String value2) {
            addCriterion("TOOTH_PASTE_TYPE not between", value1, value2, "toothPasteType");
            return (Criteria) this;
        }

        public Criteria andCleaningAidsIsNull() {
            addCriterion("CLEANING_AIDS is null");
            return (Criteria) this;
        }

        public Criteria andCleaningAidsIsNotNull() {
            addCriterion("CLEANING_AIDS is not null");
            return (Criteria) this;
        }

        public Criteria andCleaningAidsEqualTo(String value) {
            addCriterion("CLEANING_AIDS =", value, "cleaningAids");
            return (Criteria) this;
        }

        public Criteria andCleaningAidsNotEqualTo(String value) {
            addCriterion("CLEANING_AIDS <>", value, "cleaningAids");
            return (Criteria) this;
        }

        public Criteria andCleaningAidsGreaterThan(String value) {
            addCriterion("CLEANING_AIDS >", value, "cleaningAids");
            return (Criteria) this;
        }

        public Criteria andCleaningAidsGreaterThanOrEqualTo(String value) {
            addCriterion("CLEANING_AIDS >=", value, "cleaningAids");
            return (Criteria) this;
        }

        public Criteria andCleaningAidsLessThan(String value) {
            addCriterion("CLEANING_AIDS <", value, "cleaningAids");
            return (Criteria) this;
        }

        public Criteria andCleaningAidsLessThanOrEqualTo(String value) {
            addCriterion("CLEANING_AIDS <=", value, "cleaningAids");
            return (Criteria) this;
        }

        public Criteria andCleaningAidsLike(String value) {
            addCriterion("CLEANING_AIDS like", value, "cleaningAids");
            return (Criteria) this;
        }

        public Criteria andCleaningAidsNotLike(String value) {
            addCriterion("CLEANING_AIDS not like", value, "cleaningAids");
            return (Criteria) this;
        }

        public Criteria andCleaningAidsIn(List<String> values) {
            addCriterion("CLEANING_AIDS in", values, "cleaningAids");
            return (Criteria) this;
        }

        public Criteria andCleaningAidsNotIn(List<String> values) {
            addCriterion("CLEANING_AIDS not in", values, "cleaningAids");
            return (Criteria) this;
        }

        public Criteria andCleaningAidsBetween(String value1, String value2) {
            addCriterion("CLEANING_AIDS between", value1, value2, "cleaningAids");
            return (Criteria) this;
        }

        public Criteria andCleaningAidsNotBetween(String value1, String value2) {
            addCriterion("CLEANING_AIDS not between", value1, value2, "cleaningAids");
            return (Criteria) this;
        }

        public Criteria andApprovedByIsNull() {
            addCriterion("APPROVED_BY is null");
            return (Criteria) this;
        }

        public Criteria andApprovedByIsNotNull() {
            addCriterion("APPROVED_BY is not null");
            return (Criteria) this;
        }

        public Criteria andApprovedByEqualTo(String value) {
            addCriterion("APPROVED_BY =", value, "approvedBy");
            return (Criteria) this;
        }

        public Criteria andApprovedByNotEqualTo(String value) {
            addCriterion("APPROVED_BY <>", value, "approvedBy");
            return (Criteria) this;
        }

        public Criteria andApprovedByGreaterThan(String value) {
            addCriterion("APPROVED_BY >", value, "approvedBy");
            return (Criteria) this;
        }

        public Criteria andApprovedByGreaterThanOrEqualTo(String value) {
            addCriterion("APPROVED_BY >=", value, "approvedBy");
            return (Criteria) this;
        }

        public Criteria andApprovedByLessThan(String value) {
            addCriterion("APPROVED_BY <", value, "approvedBy");
            return (Criteria) this;
        }

        public Criteria andApprovedByLessThanOrEqualTo(String value) {
            addCriterion("APPROVED_BY <=", value, "approvedBy");
            return (Criteria) this;
        }

        public Criteria andApprovedByLike(String value) {
            addCriterion("APPROVED_BY like", value, "approvedBy");
            return (Criteria) this;
        }

        public Criteria andApprovedByNotLike(String value) {
            addCriterion("APPROVED_BY not like", value, "approvedBy");
            return (Criteria) this;
        }

        public Criteria andApprovedByIn(List<String> values) {
            addCriterion("APPROVED_BY in", values, "approvedBy");
            return (Criteria) this;
        }

        public Criteria andApprovedByNotIn(List<String> values) {
            addCriterion("APPROVED_BY not in", values, "approvedBy");
            return (Criteria) this;
        }

        public Criteria andApprovedByBetween(String value1, String value2) {
            addCriterion("APPROVED_BY between", value1, value2, "approvedBy");
            return (Criteria) this;
        }

        public Criteria andApprovedByNotBetween(String value1, String value2) {
            addCriterion("APPROVED_BY not between", value1, value2, "approvedBy");
            return (Criteria) this;
        }

        public Criteria andCommentIsNull() {
            addCriterion("COMMENT is null");
            return (Criteria) this;
        }

        public Criteria andCommentIsNotNull() {
            addCriterion("COMMENT is not null");
            return (Criteria) this;
        }

        public Criteria andCommentEqualTo(String value) {
            addCriterion("COMMENT =", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentNotEqualTo(String value) {
            addCriterion("COMMENT <>", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentGreaterThan(String value) {
            addCriterion("COMMENT >", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentGreaterThanOrEqualTo(String value) {
            addCriterion("COMMENT >=", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentLessThan(String value) {
            addCriterion("COMMENT <", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentLessThanOrEqualTo(String value) {
            addCriterion("COMMENT <=", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentLike(String value) {
            addCriterion("COMMENT like", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentNotLike(String value) {
            addCriterion("COMMENT not like", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentIn(List<String> values) {
            addCriterion("COMMENT in", values, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentNotIn(List<String> values) {
            addCriterion("COMMENT not in", values, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentBetween(String value1, String value2) {
            addCriterion("COMMENT between", value1, value2, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentNotBetween(String value1, String value2) {
            addCriterion("COMMENT not between", value1, value2, "comment");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("STATUS is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Byte value) {
            addCriterion("STATUS =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Byte value) {
            addCriterion("STATUS <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Byte value) {
            addCriterion("STATUS >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Byte value) {
            addCriterion("STATUS >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Byte value) {
            addCriterion("STATUS <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Byte value) {
            addCriterion("STATUS <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Byte> values) {
            addCriterion("STATUS in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Byte> values) {
            addCriterion("STATUS not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Byte value1, Byte value2) {
            addCriterion("STATUS between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Byte value1, Byte value2) {
            addCriterion("STATUS not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andSortOrderIsNull() {
            addCriterion("SORT_ORDER is null");
            return (Criteria) this;
        }

        public Criteria andSortOrderIsNotNull() {
            addCriterion("SORT_ORDER is not null");
            return (Criteria) this;
        }

        public Criteria andSortOrderEqualTo(Integer value) {
            addCriterion("SORT_ORDER =", value, "sortOrder");
            return (Criteria) this;
        }

        public Criteria andSortOrderNotEqualTo(Integer value) {
            addCriterion("SORT_ORDER <>", value, "sortOrder");
            return (Criteria) this;
        }

        public Criteria andSortOrderGreaterThan(Integer value) {
            addCriterion("SORT_ORDER >", value, "sortOrder");
            return (Criteria) this;
        }

        public Criteria andSortOrderGreaterThanOrEqualTo(Integer value) {
            addCriterion("SORT_ORDER >=", value, "sortOrder");
            return (Criteria) this;
        }

        public Criteria andSortOrderLessThan(Integer value) {
            addCriterion("SORT_ORDER <", value, "sortOrder");
            return (Criteria) this;
        }

        public Criteria andSortOrderLessThanOrEqualTo(Integer value) {
            addCriterion("SORT_ORDER <=", value, "sortOrder");
            return (Criteria) this;
        }

        public Criteria andSortOrderIn(List<Integer> values) {
            addCriterion("SORT_ORDER in", values, "sortOrder");
            return (Criteria) this;
        }

        public Criteria andSortOrderNotIn(List<Integer> values) {
            addCriterion("SORT_ORDER not in", values, "sortOrder");
            return (Criteria) this;
        }

        public Criteria andSortOrderBetween(Integer value1, Integer value2) {
            addCriterion("SORT_ORDER between", value1, value2, "sortOrder");
            return (Criteria) this;
        }

        public Criteria andSortOrderNotBetween(Integer value1, Integer value2) {
            addCriterion("SORT_ORDER not between", value1, value2, "sortOrder");
            return (Criteria) this;
        }

        public Criteria andInsertUserIdIsNull() {
            addCriterion("INSERT_USER_ID is null");
            return (Criteria) this;
        }

        public Criteria andInsertUserIdIsNotNull() {
            addCriterion("INSERT_USER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andInsertUserIdEqualTo(String value) {
            addCriterion("INSERT_USER_ID =", value, "insertUserId");
            return (Criteria) this;
        }

        public Criteria andInsertUserIdNotEqualTo(String value) {
            addCriterion("INSERT_USER_ID <>", value, "insertUserId");
            return (Criteria) this;
        }

        public Criteria andInsertUserIdGreaterThan(String value) {
            addCriterion("INSERT_USER_ID >", value, "insertUserId");
            return (Criteria) this;
        }

        public Criteria andInsertUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("INSERT_USER_ID >=", value, "insertUserId");
            return (Criteria) this;
        }

        public Criteria andInsertUserIdLessThan(String value) {
            addCriterion("INSERT_USER_ID <", value, "insertUserId");
            return (Criteria) this;
        }

        public Criteria andInsertUserIdLessThanOrEqualTo(String value) {
            addCriterion("INSERT_USER_ID <=", value, "insertUserId");
            return (Criteria) this;
        }

        public Criteria andInsertUserIdLike(String value) {
            addCriterion("INSERT_USER_ID like", value, "insertUserId");
            return (Criteria) this;
        }

        public Criteria andInsertUserIdNotLike(String value) {
            addCriterion("INSERT_USER_ID not like", value, "insertUserId");
            return (Criteria) this;
        }

        public Criteria andInsertUserIdIn(List<String> values) {
            addCriterion("INSERT_USER_ID in", values, "insertUserId");
            return (Criteria) this;
        }

        public Criteria andInsertUserIdNotIn(List<String> values) {
            addCriterion("INSERT_USER_ID not in", values, "insertUserId");
            return (Criteria) this;
        }

        public Criteria andInsertUserIdBetween(String value1, String value2) {
            addCriterion("INSERT_USER_ID between", value1, value2, "insertUserId");
            return (Criteria) this;
        }

        public Criteria andInsertUserIdNotBetween(String value1, String value2) {
            addCriterion("INSERT_USER_ID not between", value1, value2, "insertUserId");
            return (Criteria) this;
        }

        public Criteria andInsertDatetimeIsNull() {
            addCriterion("INSERT_DATETIME is null");
            return (Criteria) this;
        }

        public Criteria andInsertDatetimeIsNotNull() {
            addCriterion("INSERT_DATETIME is not null");
            return (Criteria) this;
        }

        public Criteria andInsertDatetimeEqualTo(Date value) {
            addCriterion("INSERT_DATETIME =", value, "insertDatetime");
            return (Criteria) this;
        }

        public Criteria andInsertDatetimeNotEqualTo(Date value) {
            addCriterion("INSERT_DATETIME <>", value, "insertDatetime");
            return (Criteria) this;
        }

        public Criteria andInsertDatetimeGreaterThan(Date value) {
            addCriterion("INSERT_DATETIME >", value, "insertDatetime");
            return (Criteria) this;
        }

        public Criteria andInsertDatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("INSERT_DATETIME >=", value, "insertDatetime");
            return (Criteria) this;
        }

        public Criteria andInsertDatetimeLessThan(Date value) {
            addCriterion("INSERT_DATETIME <", value, "insertDatetime");
            return (Criteria) this;
        }

        public Criteria andInsertDatetimeLessThanOrEqualTo(Date value) {
            addCriterion("INSERT_DATETIME <=", value, "insertDatetime");
            return (Criteria) this;
        }

        public Criteria andInsertDatetimeIn(List<Date> values) {
            addCriterion("INSERT_DATETIME in", values, "insertDatetime");
            return (Criteria) this;
        }

        public Criteria andInsertDatetimeNotIn(List<Date> values) {
            addCriterion("INSERT_DATETIME not in", values, "insertDatetime");
            return (Criteria) this;
        }

        public Criteria andInsertDatetimeBetween(Date value1, Date value2) {
            addCriterion("INSERT_DATETIME between", value1, value2, "insertDatetime");
            return (Criteria) this;
        }

        public Criteria andInsertDatetimeNotBetween(Date value1, Date value2) {
            addCriterion("INSERT_DATETIME not between", value1, value2, "insertDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdIsNull() {
            addCriterion("UPDATE_USER_ID is null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdIsNotNull() {
            addCriterion("UPDATE_USER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdEqualTo(String value) {
            addCriterion("UPDATE_USER_ID =", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotEqualTo(String value) {
            addCriterion("UPDATE_USER_ID <>", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdGreaterThan(String value) {
            addCriterion("UPDATE_USER_ID >", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("UPDATE_USER_ID >=", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdLessThan(String value) {
            addCriterion("UPDATE_USER_ID <", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdLessThanOrEqualTo(String value) {
            addCriterion("UPDATE_USER_ID <=", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdLike(String value) {
            addCriterion("UPDATE_USER_ID like", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotLike(String value) {
            addCriterion("UPDATE_USER_ID not like", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdIn(List<String> values) {
            addCriterion("UPDATE_USER_ID in", values, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotIn(List<String> values) {
            addCriterion("UPDATE_USER_ID not in", values, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdBetween(String value1, String value2) {
            addCriterion("UPDATE_USER_ID between", value1, value2, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotBetween(String value1, String value2) {
            addCriterion("UPDATE_USER_ID not between", value1, value2, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeIsNull() {
            addCriterion("UPDATE_DATETIME is null");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeIsNotNull() {
            addCriterion("UPDATE_DATETIME is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeEqualTo(Date value) {
            addCriterion("UPDATE_DATETIME =", value, "updateDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeNotEqualTo(Date value) {
            addCriterion("UPDATE_DATETIME <>", value, "updateDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeGreaterThan(Date value) {
            addCriterion("UPDATE_DATETIME >", value, "updateDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("UPDATE_DATETIME >=", value, "updateDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeLessThan(Date value) {
            addCriterion("UPDATE_DATETIME <", value, "updateDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeLessThanOrEqualTo(Date value) {
            addCriterion("UPDATE_DATETIME <=", value, "updateDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeIn(List<Date> values) {
            addCriterion("UPDATE_DATETIME in", values, "updateDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeNotIn(List<Date> values) {
            addCriterion("UPDATE_DATETIME not in", values, "updateDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeBetween(Date value1, Date value2) {
            addCriterion("UPDATE_DATETIME between", value1, value2, "updateDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeNotBetween(Date value1, Date value2) {
            addCriterion("UPDATE_DATETIME not between", value1, value2, "updateDatetime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tbl_patient_plaque_control
     *
     * @mbg.generated do_not_delete_during_merge Tue Dec 19 03:23:32 IST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tbl_patient_plaque_control
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }
    }
}