package com.doerit.model.diagnostic;

import java.util.Date;

public class PlaqueControl {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_patient_plaque_control.ID
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_patient_plaque_control.ITEM
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    private String item;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_patient_plaque_control.OPTION
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    private String option;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_patient_plaque_control.BRUSHING_TOOL
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    private String brushingTool;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_patient_plaque_control.BRUSHING_FREQUENCY
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    private String brushingFrequency;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_patient_plaque_control.BRISTLES
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    private String bristles;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_patient_plaque_control.BRUSHING_DURATION
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    private String brushingDuration;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_patient_plaque_control.TOOTH_PASTE_TYPE
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    private String toothPasteType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_patient_plaque_control.CLEANING_AIDS
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    private String cleaningAids;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_patient_plaque_control.APPROVED_BY
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    private String approvedBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_patient_plaque_control.COMMENT
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    private String comment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_patient_plaque_control.STATUS
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_patient_plaque_control.SORT_ORDER
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    private Integer sortOrder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_patient_plaque_control.INSERT_USER_ID
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    private String insertUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_patient_plaque_control.INSERT_DATETIME
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    private Date insertDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_patient_plaque_control.UPDATE_USER_ID
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    private String updateUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_patient_plaque_control.UPDATE_DATETIME
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    private Date updateDatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_patient_plaque_control.ID
     *
     * @return the value of tbl_patient_plaque_control.ID
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_patient_plaque_control.ID
     *
     * @param id the value for tbl_patient_plaque_control.ID
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_patient_plaque_control.ITEM
     *
     * @return the value of tbl_patient_plaque_control.ITEM
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public String getItem() {
        return item;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_patient_plaque_control.ITEM
     *
     * @param item the value for tbl_patient_plaque_control.ITEM
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public void setItem(String item) {
        this.item = item == null ? null : item.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_patient_plaque_control.OPTION
     *
     * @return the value of tbl_patient_plaque_control.OPTION
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public String getOption() {
        return option;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_patient_plaque_control.OPTION
     *
     * @param option the value for tbl_patient_plaque_control.OPTION
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public void setOption(String option) {
        this.option = option == null ? null : option.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_patient_plaque_control.BRUSHING_TOOL
     *
     * @return the value of tbl_patient_plaque_control.BRUSHING_TOOL
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public String getBrushingTool() {
        return brushingTool;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_patient_plaque_control.BRUSHING_TOOL
     *
     * @param brushingTool the value for tbl_patient_plaque_control.BRUSHING_TOOL
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public void setBrushingTool(String brushingTool) {
        this.brushingTool = brushingTool == null ? null : brushingTool.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_patient_plaque_control.BRUSHING_FREQUENCY
     *
     * @return the value of tbl_patient_plaque_control.BRUSHING_FREQUENCY
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public String getBrushingFrequency() {
        return brushingFrequency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_patient_plaque_control.BRUSHING_FREQUENCY
     *
     * @param brushingFrequency the value for tbl_patient_plaque_control.BRUSHING_FREQUENCY
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public void setBrushingFrequency(String brushingFrequency) {
        this.brushingFrequency = brushingFrequency == null ? null : brushingFrequency.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_patient_plaque_control.BRISTLES
     *
     * @return the value of tbl_patient_plaque_control.BRISTLES
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public String getBristles() {
        return bristles;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_patient_plaque_control.BRISTLES
     *
     * @param bristles the value for tbl_patient_plaque_control.BRISTLES
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public void setBristles(String bristles) {
        this.bristles = bristles == null ? null : bristles.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_patient_plaque_control.BRUSHING_DURATION
     *
     * @return the value of tbl_patient_plaque_control.BRUSHING_DURATION
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public String getBrushingDuration() {
        return brushingDuration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_patient_plaque_control.BRUSHING_DURATION
     *
     * @param brushingDuration the value for tbl_patient_plaque_control.BRUSHING_DURATION
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public void setBrushingDuration(String brushingDuration) {
        this.brushingDuration = brushingDuration == null ? null : brushingDuration.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_patient_plaque_control.TOOTH_PASTE_TYPE
     *
     * @return the value of tbl_patient_plaque_control.TOOTH_PASTE_TYPE
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public String getToothPasteType() {
        return toothPasteType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_patient_plaque_control.TOOTH_PASTE_TYPE
     *
     * @param toothPasteType the value for tbl_patient_plaque_control.TOOTH_PASTE_TYPE
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public void setToothPasteType(String toothPasteType) {
        this.toothPasteType = toothPasteType == null ? null : toothPasteType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_patient_plaque_control.CLEANING_AIDS
     *
     * @return the value of tbl_patient_plaque_control.CLEANING_AIDS
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public String getCleaningAids() {
        return cleaningAids;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_patient_plaque_control.CLEANING_AIDS
     *
     * @param cleaningAids the value for tbl_patient_plaque_control.CLEANING_AIDS
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public void setCleaningAids(String cleaningAids) {
        this.cleaningAids = cleaningAids == null ? null : cleaningAids.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_patient_plaque_control.APPROVED_BY
     *
     * @return the value of tbl_patient_plaque_control.APPROVED_BY
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public String getApprovedBy() {
        return approvedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_patient_plaque_control.APPROVED_BY
     *
     * @param approvedBy the value for tbl_patient_plaque_control.APPROVED_BY
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public void setApprovedBy(String approvedBy) {
        this.approvedBy = approvedBy == null ? null : approvedBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_patient_plaque_control.COMMENT
     *
     * @return the value of tbl_patient_plaque_control.COMMENT
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_patient_plaque_control.COMMENT
     *
     * @param comment the value for tbl_patient_plaque_control.COMMENT
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_patient_plaque_control.STATUS
     *
     * @return the value of tbl_patient_plaque_control.STATUS
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_patient_plaque_control.STATUS
     *
     * @param status the value for tbl_patient_plaque_control.STATUS
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_patient_plaque_control.SORT_ORDER
     *
     * @return the value of tbl_patient_plaque_control.SORT_ORDER
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public Integer getSortOrder() {
        return sortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_patient_plaque_control.SORT_ORDER
     *
     * @param sortOrder the value for tbl_patient_plaque_control.SORT_ORDER
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public void setSortOrder(Integer sortOrder) {
        this.sortOrder = sortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_patient_plaque_control.INSERT_USER_ID
     *
     * @return the value of tbl_patient_plaque_control.INSERT_USER_ID
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public String getInsertUserId() {
        return insertUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_patient_plaque_control.INSERT_USER_ID
     *
     * @param insertUserId the value for tbl_patient_plaque_control.INSERT_USER_ID
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public void setInsertUserId(String insertUserId) {
        this.insertUserId = insertUserId == null ? null : insertUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_patient_plaque_control.INSERT_DATETIME
     *
     * @return the value of tbl_patient_plaque_control.INSERT_DATETIME
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public Date getInsertDatetime() {
        return insertDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_patient_plaque_control.INSERT_DATETIME
     *
     * @param insertDatetime the value for tbl_patient_plaque_control.INSERT_DATETIME
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public void setInsertDatetime(Date insertDatetime) {
        this.insertDatetime = insertDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_patient_plaque_control.UPDATE_USER_ID
     *
     * @return the value of tbl_patient_plaque_control.UPDATE_USER_ID
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public String getUpdateUserId() {
        return updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_patient_plaque_control.UPDATE_USER_ID
     *
     * @param updateUserId the value for tbl_patient_plaque_control.UPDATE_USER_ID
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public void setUpdateUserId(String updateUserId) {
        this.updateUserId = updateUserId == null ? null : updateUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_patient_plaque_control.UPDATE_DATETIME
     *
     * @return the value of tbl_patient_plaque_control.UPDATE_DATETIME
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public Date getUpdateDatetime() {
        return updateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_patient_plaque_control.UPDATE_DATETIME
     *
     * @param updateDatetime the value for tbl_patient_plaque_control.UPDATE_DATETIME
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    public void setUpdateDatetime(Date updateDatetime) {
        this.updateDatetime = updateDatetime;
    }
}