CREATE TABLE IF NOT EXISTS `dental_db`.`tbl_patient_habit` (
  `ID` CHAR(32) NOT NULL,
  `PATIENT_ID` CHAR(32) NOT NULL,
  `HABIT_ID` CHAR(32) NOT NULL,
  `FREQUENCY` CHAR(128) NULL,
  `DURATION` CHAR(128) NULL,
  `DATA_ADDED_BY` CHAR(32) NULL,
  `APPROVED_BY` CHAR(32) NULL DEFAULT NULL,
  `COMMENT` CHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `STATUS` TINYINT(4) NULL DEFAULT '0',
  `SORT_ORDER` INT(6) NULL DEFAULT '1',
  `INSERT_USER_ID` CHAR(32) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `INSERT_DATETIME` DATETIME NULL DEFAULT NULL,
  `UPDATE_USER_ID` CHAR(32) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `UPDATE_DATETIME` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_tbl_patient_habit_tbl_habit1_idx` (`HABIT_ID` ASC),
  CONSTRAINT `fk_tbl_patient_habit_tbl_habit1`
    FOREIGN KEY (`HABIT_ID`)
    REFERENCES `dental_db`.`tbl_habit` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
