DROP TABLE IF EXISTS tbl_complaint.sql;

CREATE TABLE IF NOT EXISTS `dental_db`.`tbl_complaint` (
  `ID` CHAR(32) NOT NULL,
  `COMPLAINT` CHAR(128) NULL DEFAULT NULL,
  `TYPE` CHAR(32) NULL DEFAULT NULL,
  `COMPLAINT_HISTORY` CHAR(255) NULL DEFAULT NULL,
  `APPROVED_BY` CHAR(32) NULL DEFAULT NULL,
  `COMMENT` CHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `STATUS` TINYINT(4) NULL DEFAULT '0',
  `SORT_ORDER` INT(6) NULL DEFAULT '1',
  `INSERT_USER_ID` CHAR(32) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `INSERT_DATETIME` DATETIME NULL DEFAULT NULL,
  `UPDATE_USER_ID` CHAR(32) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `UPDATE_DATETIME` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;

