package com.doerit.model;

import java.math.BigDecimal;
import java.util.Date;

public class PatientGuardian {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_patient_guardian.ID
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_patient_guardian.PATIENT_ID
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    private String patientId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_patient_guardian.NAME
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_patient_guardian.RELATIONSHIP
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    private String relationship;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_patient_guardian.TELEPHONE_HOME
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    private String telephoneHome;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_patient_guardian.TELEPHONE_MOBILE
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    private String telephoneMobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_patient_guardian.NIC
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    private String nic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_patient_guardian.OCUPATION
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    private String ocupation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_patient_guardian.MONTHLY_INCOME
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    private BigDecimal monthlyIncome;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_patient_guardian.STATUS
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_patient_guardian.SORT_ORDER
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    private Integer sortOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_patient_guardian.INSERT_USER_ID
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    private String insertUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_patient_guardian.UPDATE_USER_ID
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    private String updateUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_patient_guardian.INSERT_DATETIME
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    private Date insertDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_patient_guardian.UPDATE_DATETIME
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    private Date updateDatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_patient_guardian.ID
     *
     * @return the value of tbl_patient_guardian.ID
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_patient_guardian.ID
     *
     * @param id the value for tbl_patient_guardian.ID
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_patient_guardian.PATIENT_ID
     *
     * @return the value of tbl_patient_guardian.PATIENT_ID
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    public String getPatientId() {
        return patientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_patient_guardian.PATIENT_ID
     *
     * @param patientId the value for tbl_patient_guardian.PATIENT_ID
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    public void setPatientId(String patientId) {
        this.patientId = patientId == null ? null : patientId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_patient_guardian.NAME
     *
     * @return the value of tbl_patient_guardian.NAME
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_patient_guardian.NAME
     *
     * @param name the value for tbl_patient_guardian.NAME
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_patient_guardian.RELATIONSHIP
     *
     * @return the value of tbl_patient_guardian.RELATIONSHIP
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    public String getRelationship() {
        return relationship;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_patient_guardian.RELATIONSHIP
     *
     * @param relationship the value for tbl_patient_guardian.RELATIONSHIP
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    public void setRelationship(String relationship) {
        this.relationship = relationship == null ? null : relationship.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_patient_guardian.TELEPHONE_HOME
     *
     * @return the value of tbl_patient_guardian.TELEPHONE_HOME
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    public String getTelephoneHome() {
        return telephoneHome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_patient_guardian.TELEPHONE_HOME
     *
     * @param telephoneHome the value for tbl_patient_guardian.TELEPHONE_HOME
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    public void setTelephoneHome(String telephoneHome) {
        this.telephoneHome = telephoneHome == null ? null : telephoneHome.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_patient_guardian.TELEPHONE_MOBILE
     *
     * @return the value of tbl_patient_guardian.TELEPHONE_MOBILE
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    public String getTelephoneMobile() {
        return telephoneMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_patient_guardian.TELEPHONE_MOBILE
     *
     * @param telephoneMobile the value for tbl_patient_guardian.TELEPHONE_MOBILE
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    public void setTelephoneMobile(String telephoneMobile) {
        this.telephoneMobile = telephoneMobile == null ? null : telephoneMobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_patient_guardian.NIC
     *
     * @return the value of tbl_patient_guardian.NIC
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    public String getNic() {
        return nic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_patient_guardian.NIC
     *
     * @param nic the value for tbl_patient_guardian.NIC
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    public void setNic(String nic) {
        this.nic = nic == null ? null : nic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_patient_guardian.OCUPATION
     *
     * @return the value of tbl_patient_guardian.OCUPATION
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    public String getOcupation() {
        return ocupation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_patient_guardian.OCUPATION
     *
     * @param ocupation the value for tbl_patient_guardian.OCUPATION
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    public void setOcupation(String ocupation) {
        this.ocupation = ocupation == null ? null : ocupation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_patient_guardian.MONTHLY_INCOME
     *
     * @return the value of tbl_patient_guardian.MONTHLY_INCOME
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    public BigDecimal getMonthlyIncome() {
        return monthlyIncome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_patient_guardian.MONTHLY_INCOME
     *
     * @param monthlyIncome the value for tbl_patient_guardian.MONTHLY_INCOME
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    public void setMonthlyIncome(BigDecimal monthlyIncome) {
        this.monthlyIncome = monthlyIncome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_patient_guardian.STATUS
     *
     * @return the value of tbl_patient_guardian.STATUS
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_patient_guardian.STATUS
     *
     * @param status the value for tbl_patient_guardian.STATUS
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_patient_guardian.SORT_ORDER
     *
     * @return the value of tbl_patient_guardian.SORT_ORDER
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    public Integer getSortOrder() {
        return sortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_patient_guardian.SORT_ORDER
     *
     * @param sortOrder the value for tbl_patient_guardian.SORT_ORDER
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    public void setSortOrder(Integer sortOrder) {
        this.sortOrder = sortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_patient_guardian.INSERT_USER_ID
     *
     * @return the value of tbl_patient_guardian.INSERT_USER_ID
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    public String getInsertUserId() {
        return insertUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_patient_guardian.INSERT_USER_ID
     *
     * @param insertUserId the value for tbl_patient_guardian.INSERT_USER_ID
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    public void setInsertUserId(String insertUserId) {
        this.insertUserId = insertUserId == null ? null : insertUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_patient_guardian.UPDATE_USER_ID
     *
     * @return the value of tbl_patient_guardian.UPDATE_USER_ID
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    public String getUpdateUserId() {
        return updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_patient_guardian.UPDATE_USER_ID
     *
     * @param updateUserId the value for tbl_patient_guardian.UPDATE_USER_ID
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    public void setUpdateUserId(String updateUserId) {
        this.updateUserId = updateUserId == null ? null : updateUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_patient_guardian.INSERT_DATETIME
     *
     * @return the value of tbl_patient_guardian.INSERT_DATETIME
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    public Date getInsertDatetime() {
        return insertDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_patient_guardian.INSERT_DATETIME
     *
     * @param insertDatetime the value for tbl_patient_guardian.INSERT_DATETIME
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    public void setInsertDatetime(Date insertDatetime) {
        this.insertDatetime = insertDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_patient_guardian.UPDATE_DATETIME
     *
     * @return the value of tbl_patient_guardian.UPDATE_DATETIME
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    public Date getUpdateDatetime() {
        return updateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_patient_guardian.UPDATE_DATETIME
     *
     * @param updateDatetime the value for tbl_patient_guardian.UPDATE_DATETIME
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    public void setUpdateDatetime(Date updateDatetime) {
        this.updateDatetime = updateDatetime;
    }
}