package com.doerit.dao;

import com.doerit.model.diagnostic.Complaint;
import com.doerit.model.diagnostic.ComplaintExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ComplaintMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_complaint
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    long countByExample(ComplaintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_complaint
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    int deleteByExample(ComplaintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_complaint
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_complaint
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    int insert(Complaint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_complaint
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    int insertSelective(Complaint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_complaint
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    List<Complaint> selectByExample(ComplaintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_complaint
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    Complaint selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_complaint
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    int updateByExampleSelective(@Param("record") Complaint record, @Param("example") ComplaintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_complaint
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    int updateByExample(@Param("record") Complaint record, @Param("example") ComplaintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_complaint
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    int updateByPrimaryKeySelective(Complaint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_complaint
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    int updateByPrimaryKey(Complaint record);
}