package com.doerit.dao;

import com.doerit.model.diagnostic.DiagnosticReport;
import com.doerit.model.diagnostic.DiagnosticReportExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DiagnosticReportMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_patient_diagnostic_report
     *
     * @mbg.generated Tue Dec 19 03:32:57 IST 2017
     */
    long countByExample(DiagnosticReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_patient_diagnostic_report
     *
     * @mbg.generated Tue Dec 19 03:32:57 IST 2017
     */
    int deleteByExample(DiagnosticReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_patient_diagnostic_report
     *
     * @mbg.generated Tue Dec 19 03:32:57 IST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_patient_diagnostic_report
     *
     * @mbg.generated Tue Dec 19 03:32:57 IST 2017
     */
    int insert(DiagnosticReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_patient_diagnostic_report
     *
     * @mbg.generated Tue Dec 19 03:32:57 IST 2017
     */
    int insertSelective(DiagnosticReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_patient_diagnostic_report
     *
     * @mbg.generated Tue Dec 19 03:32:57 IST 2017
     */
    List<DiagnosticReport> selectByExample(DiagnosticReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_patient_diagnostic_report
     *
     * @mbg.generated Tue Dec 19 03:32:57 IST 2017
     */
    DiagnosticReport selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_patient_diagnostic_report
     *
     * @mbg.generated Tue Dec 19 03:32:57 IST 2017
     */
    int updateByExampleSelective(@Param("record") DiagnosticReport record, @Param("example") DiagnosticReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_patient_diagnostic_report
     *
     * @mbg.generated Tue Dec 19 03:32:57 IST 2017
     */
    int updateByExample(@Param("record") DiagnosticReport record, @Param("example") DiagnosticReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_patient_diagnostic_report
     *
     * @mbg.generated Tue Dec 19 03:32:57 IST 2017
     */
    int updateByPrimaryKeySelective(DiagnosticReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_patient_diagnostic_report
     *
     * @mbg.generated Tue Dec 19 03:32:57 IST 2017
     */
    int updateByPrimaryKey(DiagnosticReport record);
}