package com.doerit.dao;

import com.doerit.model.diagnostic.DietaryHistory;
import com.doerit.model.diagnostic.DietaryHistoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DietaryHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_patient_dietary_history
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    long countByExample(DietaryHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_patient_dietary_history
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    int deleteByExample(DietaryHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_patient_dietary_history
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_patient_dietary_history
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    int insert(DietaryHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_patient_dietary_history
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    int insertSelective(DietaryHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_patient_dietary_history
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    List<DietaryHistory> selectByExample(DietaryHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_patient_dietary_history
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    DietaryHistory selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_patient_dietary_history
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    int updateByExampleSelective(@Param("record") DietaryHistory record, @Param("example") DietaryHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_patient_dietary_history
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    int updateByExample(@Param("record") DietaryHistory record, @Param("example") DietaryHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_patient_dietary_history
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    int updateByPrimaryKeySelective(DietaryHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_patient_dietary_history
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    int updateByPrimaryKey(DietaryHistory record);
}