package com.doerit.dao;

import com.doerit.model.diagnostic.Drug;
import com.doerit.model.diagnostic.DrugExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DrugMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_drug
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    long countByExample(DrugExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_drug
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    int deleteByExample(DrugExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_drug
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_drug
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    int insert(Drug record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_drug
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    int insertSelective(Drug record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_drug
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    List<Drug> selectByExample(DrugExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_drug
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    Drug selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_drug
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    int updateByExampleSelective(@Param("record") Drug record, @Param("example") DrugExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_drug
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    int updateByExample(@Param("record") Drug record, @Param("example") DrugExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_drug
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    int updateByPrimaryKeySelective(Drug record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_drug
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    int updateByPrimaryKey(Drug record);
}