package com.doerit.dao;

import com.doerit.model.diagnostic.DrugHistory;
import com.doerit.model.diagnostic.DrugHistoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DrugHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_patient_drug_history
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    long countByExample(DrugHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_patient_drug_history
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    int deleteByExample(DrugHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_patient_drug_history
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_patient_drug_history
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    int insert(DrugHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_patient_drug_history
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    int insertSelective(DrugHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_patient_drug_history
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    List<DrugHistory> selectByExample(DrugHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_patient_drug_history
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    DrugHistory selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_patient_drug_history
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    int updateByExampleSelective(@Param("record") DrugHistory record, @Param("example") DrugHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_patient_drug_history
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    int updateByExample(@Param("record") DrugHistory record, @Param("example") DrugHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_patient_drug_history
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    int updateByPrimaryKeySelective(DrugHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_patient_drug_history
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    int updateByPrimaryKey(DrugHistory record);
}