package com.doerit.dao;

import com.doerit.model.diagnostic.PatientHabit;
import com.doerit.model.diagnostic.PatientHabitExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PatientHabitMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_patient_habit
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    long countByExample(PatientHabitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_patient_habit
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    int deleteByExample(PatientHabitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_patient_habit
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_patient_habit
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    int insert(PatientHabit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_patient_habit
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    int insertSelective(PatientHabit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_patient_habit
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    List<PatientHabit> selectByExample(PatientHabitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_patient_habit
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    PatientHabit selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_patient_habit
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    int updateByExampleSelective(@Param("record") PatientHabit record, @Param("example") PatientHabitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_patient_habit
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    int updateByExample(@Param("record") PatientHabit record, @Param("example") PatientHabitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_patient_habit
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    int updateByPrimaryKeySelective(PatientHabit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_patient_habit
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    int updateByPrimaryKey(PatientHabit record);
}