package com.doerit.dao;

import com.doerit.model.PatientGuardian;
import com.doerit.model.PatientGuardianExample;
import com.doerit.model.PatientGuardianWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PatientGuardianMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_patient_guardian
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    int countByExample(PatientGuardianExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_patient_guardian
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    int deleteByExample(PatientGuardianExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_patient_guardian
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_patient_guardian
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    int insert(PatientGuardianWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_patient_guardian
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    int insertSelective(PatientGuardianWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_patient_guardian
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    List<PatientGuardianWithBLOBs> selectByExampleWithBLOBs(PatientGuardianExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_patient_guardian
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    List<PatientGuardian> selectByExample(PatientGuardianExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_patient_guardian
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    PatientGuardianWithBLOBs selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_patient_guardian
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    int updateByExampleSelective(@Param("record") PatientGuardianWithBLOBs record, @Param("example") PatientGuardianExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_patient_guardian
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") PatientGuardianWithBLOBs record, @Param("example") PatientGuardianExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_patient_guardian
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    int updateByExample(@Param("record") PatientGuardian record, @Param("example") PatientGuardianExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_patient_guardian
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    int updateByPrimaryKeySelective(PatientGuardianWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_patient_guardian
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    int updateByPrimaryKeyWithBLOBs(PatientGuardianWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_patient_guardian
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    int updateByPrimaryKey(PatientGuardian record);
}