package com.doerit.dao;

import com.doerit.model.diagnostic.PlaqueControl;
import com.doerit.model.diagnostic.PlaqueControlExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PlaqueControlMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_patient_plaque_control
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    long countByExample(PlaqueControlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_patient_plaque_control
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    int deleteByExample(PlaqueControlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_patient_plaque_control
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_patient_plaque_control
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    int insert(PlaqueControl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_patient_plaque_control
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    int insertSelective(PlaqueControl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_patient_plaque_control
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    List<PlaqueControl> selectByExample(PlaqueControlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_patient_plaque_control
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    PlaqueControl selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_patient_plaque_control
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    int updateByExampleSelective(@Param("record") PlaqueControl record, @Param("example") PlaqueControlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_patient_plaque_control
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    int updateByExample(@Param("record") PlaqueControl record, @Param("example") PlaqueControlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_patient_plaque_control
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    int updateByPrimaryKeySelective(PlaqueControl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_patient_plaque_control
     *
     * @mbg.generated Tue Dec 19 03:23:32 IST 2017
     */
    int updateByPrimaryKey(PlaqueControl record);
}